### ISSUE TITLE
Failed to archive event.

### ISSUE THREAD

**Issue by banjoey** [jasonish/evebox#10]
Evebox worked without a hitch until we updated our elasticsearch cluster. Now when I try to archive I get a "Failed to archive event." message. We have updated our elasticsearch.yml to allow CORS and Dynamic Scripting. I'm happy to help troubleshoot this if you can point me to any debug logs that I can turn on (or view).

We do not run ELK on the same box as evebox. We have a dedicated cluster set up. I'm using the latest release of evebox from master.

**Comment by jasonish** [comment]
I've tested the current master on Elastic Search 1.4.4 and recently upgraded to 1.5.0 and it seems to be working fine, at least for me.

One problem area I've seen before is browser caching.  Can you try clearing your browser cache and/or force reloading the page?

While conveying better error messages to the user is something that I need to work on, you can usually see whats going on by opening up the Javascript developer console.  In Chrome this can be found under the menu "More Tools -> JavaScript console".  Most errors get dumped there in a more raw format.

Can you tell me what version of Elastic Search you are using?  As well as what browser?

**Comment by banjoey** [comment]
Looks like our puppet update didn't restart elasticsearch after the config changes. Works like a charm now! Sorry for the inconvenience...
