### ISSUE TITLE
DNS and Alert Reports over all Time

### ISSUE THREAD

**Issue by Manwendil** [jasonish/evebox#103]

**Comment by Manwendil** [comment]
DNS and Alert Reports over all Time produces no output (No Data). All specific Time Ranges working well, also all other kinds of reports over all Time.

**Comment by jasonish** [comment]
Closing. I think this might have been related to the bucket sizes which has been fixed in master.  Though could still creep in I suppose.  I'll need Elasticsearch logs to debug further.
