### ISSUE TITLE
Unhandled error on events tab with an unknown event

### ISSUE THREAD

**Issue by sonicold** [jasonish/evebox#105]
## How to reproduce
Go on `Events` tab and click on an event

## Software version
version: 0.10.2 (Rev: 56b673c)
browser: chrome

## What's oberved
`Unhandled error` whith blank screen
![evebox2](https://user-images.githubusercontent.com/194868/55712074-5edad900-59ee-11e9-8444-492a7ad56c92.png)

**Comment by jasonish** [comment]
How are you adding events to Elastic Search?

**Comment by sonicold** [comment]
Sorry for the very late answer !
I am adding events with filebeat and logstash.

**Comment by jasonish** [comment]
If you haven't already, I suggest updating to 0.11.1 or the latest development build and trying again if you like:

Development builds:
https://evebox.org/files/development/

Release builds:
https://evebox.org/files/release/latest/

**Comment by sonicold** [comment]
Thank you, it worked with 0.11.1
