### ISSUE TITLE
 (datastore-eventquery.go:87) <Error> -- json: cannot unmarshal object into Go struct field Hits.total of type uint64

### ISSUE THREAD

**Issue by mounaBoo** [jasonish/evebox#107]
I installed evebox with elasticsearch version 5 and it's working just fine,
I tried to install it with elasticsearch version 7 , I did the same configuration for logtash to ship data into elasticsearch ( the configuration was ok and elasticsearch created index

but I don't get any event on evebox and it gives me this error: 

 (datastore-eventquery.go:87) <Error> -- json: cannot unmarshal object into Go struct field Hits.total of type uint64

![ff](https://user-images.githubusercontent.com/23616955/57589881-0a5bd980-7517-11e9-9b0e-a7cf535448e8.PNG)
![tb](https://user-images.githubusercontent.com/23616955/57589882-0a5bd980-7517-11e9-96c5-e1f65a219c64.PNG)
![tgbn](https://user-images.githubusercontent.com/23616955/57589883-0a5bd980-7517-11e9-98e8-4ca80c098161.PNG)

**Comment by mounaBoo** [comment]
I restarted all services now I am getting :

2019-05-13 00:50:05 (elasticsearch.go:241) <Warning> -- Failed to determine Elastic Search keyword suffix, things may not work right.

**Comment by jasonish** [comment]
Sorry, I've not yet had a chance to look into Elastic Search 7 support.  I see there are a number of ES 7 breaking changes that I will have to look into.  It'll probably be a couple weeks before I look closer into it and evaluate just how much time it will take.

**Comment by mounaBoo** [comment]
thank you sir that would be great

**Comment by jasonish** [comment]
This is now fixed.  Its available in git master or as a development build:
https://evebox.org/files/development/
