### ISSUE TITLE
Elasticsearch 7.2

### ISSUE THREAD

**Issue by elhijo** [jasonish/evebox#112]
Hi Jason,

Updated to elasticsearch 7.2 to test the new SIEM module and, evebox stopped working.
Anything to get it back online or an update is needed ?

Thanks !

**Comment by jasonish** [comment]
Did you do an upgrade from 6.x to 7.x?  Looks like the 6.x template isn't fully supported.  Also, if you are using the Filebeat Suricata plugin, it adds events to ES in a format that EveBox doesn't understand.

I've only just barely tried ES 7.2 and hit these template issues.  The long term goal is to standardize around the ECS that is used by the Suricata plugin for filebeat though.

**Comment by jasonish** [comment]
Elastic Search 7 support has been fixed in master and can be had with a development build.
