### ISSUE TITLE
ES 7.3.0 - not working

### ISSUE THREAD

**Issue by myrinx** [jasonish/evebox#114]
Hi,

upgraded to ES 7.3.0 and installed the latest release on debian. Getting this error from evebox after the upgrade.

2019-08-13 11:15:15 (elasticsearch.go:260) <Warning> -- Failed to determine Elastic Search keyword suffix, things may not work right.

any clue?

**Comment by jasonish** [comment]
If you haven't not tried the development build, please do so.  I did make some fixes with respect to Elastic Search 7 there.

https://evebox.org/files/development/

**Comment by myrinx** [comment]
Yeah, i'm running that version through the dev-repo with apt. 

Fixed it though, not an evebox issue fortunately.

The thing is that elastic builds a template through logstash (in my case) which you have to remove (curl XDELETE /_template/logstash). 

replacing the elastic-6 with the elastic-7 template you've provided in the code itself works when you restart logstash. It creates a new template in elasticsearch, after which evebox finds 'keyword' as the search suffix.

case closed :)

ps. it would be awesome to be able to mass de-escalate ;)
