### ISSUE TITLE
Javascript Heap error memory

### ISSUE THREAD

**Issue by TheThingGoesSkra** [jasonish/evebox#119]
Hello, I'm trying to build evebox on a Raspberry Pi 3B+ with Raspbian but I have this error.
I have already installed and make dependencies.
Do you know where it could have come from plz ? 
 
pi@raspberrypi:/opt/evebox $ sudo make
cd webapp && make
make[1]: Entering directory '/opt/evebox/webapp'
Exporting GITREV = 9856ecf.
Building EveBox webapp rev 9856ecf.
./node_modules/.bin/ng build --aot --prod --output-path ../resources/public --deploy-url "public/" 
 68% building 488/490 modules 2 active .../theme-light.scss                 
<--- Last few GCs --->

[11693:0x333f5f8]   343030 ms: Mark-sweep 225.1 (234.5) -> 223.3 (234.5) MB, 1089.6 / 0.3 ms  (average mu = 0.258, current mu = 0.228) allocation failure scavenge might not succeed
[11693:0x333f5f8]   344653 ms: Mark-sweep 225.2 (234.5) -> 223.3 (234.5) MB, 1175.0 / 0.3 ms  (average mu = 0.267, current mu = 0.276) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0xe50420]
    1: StubFrame [pc: 0xebed84]
Security context: 0x329ce225 <JSObject>
    2: xF [0x738c5595] [/opt/evebox/webapp/node_modules/sass/sass.dart.js:1] [bytecode=0x4a042275 offset=0](this=0x6d4f8cb9 <iZ map = 0x431d1249>,0x4c217429 <cz map = 0x431d73a1>)
    3: hF [0x738c53d5] [/opt/evebox/webapp/node_modules/sass/sass.dart.js:19754] [bytecode=0x4a040a71 offset=7](this=0x6d4f8cb9 <iZ map = 0x431d1249>,0x4c2174...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20191114.160456.11693.0.001.json
Node.js report completed
Aborted
make[1]: *** [Makefile:26: build] Error 134
make[1]: Leaving directory '/opt/evebox/webapp'
make: *** [Makefile:65: resources/public/_done] Error 2

**Comment by jasonish** [comment]
This failure is coming out of the JavaScript build tools. Unfortunately I don't know these tools very well so won't be of any help.

**Comment by thiscantbeserious** [comment]
You need to increase Heap-Size for node.js (otherwise V8 is limited to 1.7GB) by exporting this enviroment variable:

export NODE_OPTIONS="--max-old-space-size=4096"

You could also fix the makefile by adding it as an argument to the build command for everything involving NodeJS. Didn't bother doing it myself tought ...

**Comment by TheThingGoesSkra** [comment]
Thank you very much ! A friend found it earlier.

**Comment by jasonish** [comment]
> You need to increase Heap-Size for node.js (otherwise V8 is limited to 1.7GB) by exporting this environment variable either temporary for the session or by adding it to your .bashrc:
> 
> export NODE_OPTIONS="--max-old-space-size=4096"
> 
> You could also fix the Makefile by adding it as an argument to the build command for everything involving NodeJS. But I recon simply using the above global options are a better way of solving this issue once and for all.

Thanks for this feedback.  I'll try to incorporate it into the build script, even if only as a comment.

**Comment by jasonish** [comment]
Closing. Added to the README.
