### ISSUE TITLE
Can't get it to work with Elastic 2.1

### ISSUE THREAD

**Issue by tsunulukai** [jasonish/evebox#12]
Hello, I used to run evebox on top of elastic v1.7.1.
I recently updated to elastic 2.1 and it seems not to work anymore.

I have tried with the following options in the elasticsearch.yml file, without success.
`http.cors.enabled: true `
`#script.disable_dynamic: false`
`script.inline: on`
`script.indexed: on`

`script.disable_dynamic` is not supported anymore in elastic 2.1 (https://github.com/elastic/elasticsearch/issues/10274)
It should be replaced by `script.inline` & `script.indexed`, but it does not seem to solve the issue when enabled.

I have tried this with with evebox v0.4.0dev without luck...
any idea ?

**Comment by jasonish** [comment]
I should probably move my development branch over to master, as I'm using it against ES 2.1.0 now.  Its stable for me, though changed a bit so I haven't made it master in git yet.  Please try it though:

https://github.com/jasonish/evebox/tree/develop

You can use the built-in backend to avoid enabling CORS, or serve up the "public" directory like you did with the "app" directory in previous versions.

**Comment by tsunulukai** [comment]
Hello,

It works with the binary version, but I still can't get it to work with the "Option 3" you describe...

**Comment by jasonish** [comment]
I was able to get it work by adding the following to my elasticsearch config:

http.cors.enabled: true
http.cors.allow-origin: "/.*/"

If that doesn't work, open the developer console in your browser please to get any errors that may be happening.

Thanks.

**Comment by jasonish** [comment]
Closing for now.
