### ISSUE TITLE
Docker image tags

### ISSUE THREAD

**Issue by sgabe** [jasonish/evebox#132]
This recent commit https://github.com/jasonish/evebox/commit/b717d2ace2e2092578ae3b6078047cf99a11dc24 to drop support for ElasticSearch versions prior to 7.7 broke my setup after you pushed this change to the `latest` image available on Docker Hub.

Pushing new versions to Docker Hub with proper tags - preferably matching the GitHub release tags - would allow users e.g. to easily see whether it is safe to upgrade the image and to identify potentially breaking changes without checking the commits prior the upgrade.

**Comment by jasonish** [comment]
When I pull `latest` from Docker hub I get 0.11.1.  If I pull the `master` tag, then I do get 0.12.0dev where I made this breaking change. Are you seeing different?

**Comment by sgabe** [comment]
I just wanted to update my original post: It seems the affected container was running on `master` so I am moving that to `latest`. Still would be nice to have tagged images on Docker Hub. Could pull the image based on the hash to be safe.

**Comment by jasonish** [comment]
I can start tagging with the version.. ie) 0.11.0, 0.11.1. But not sure about tagging with every commit hash.  Don't need to burden Docker hub with that level of detail.

**Comment by sgabe** [comment]
Of course, just tag the releases with the version number. What I meant is that I can pull the image I need based on its SHA256 digest as a quick fix.
