### ISSUE TITLE
Need help to run and access Evebox using built-in SQLite

### ISSUE THREAD

**Issue by purk4** [jasonish/evebox#138]
I installed Evebox from the stable branch of Debian repo.
I try to run Evebox inside Suricata machine (no GUI) using built-in SQLite feature, but there are issues, I think that there are some bug or the manuals are not updated.

I used these two reccomendations from user guide, but both failed to run and generated errors:
**evebox server --datastore sqlite --input /var/log/suricata/eve.json
evebox -v -D . --datastore sqlite --input /var/log/suricata/eve.json**

**********************
root@suricata:/etc# **evebox server --datastore sqlite --input /var/log/suricata/eve.json**
2020-07-02 16:09:06 (server.go:163) <Info> -- This is EveBox Server version 0.11.1 (rev: 4d1b355); os=linux, arch=amd64
2020-07-02 16:09:06 (server.go:252) <Info> -- Self test: found embedded index.html.
2020-07-02 16:09:06 (geoip-service.go:44) <Warning> -- Failed to initialize geoip database: no database files found
2020-07-02 16:09:06 (configdb.go:52) <Info> -- Using in-memory configuration DB.
2020-07-02 16:09:06 (migrator.go:79) <Info> -- Updating database to version 0.
2020-07-02 16:09:06 (migrator.go:79) <Info> -- Updating database to version 1.
2020-07-02 16:09:06 (server.go:364) <Error> -- SQLite datastore requires a data-directory

root@suricata:/etc# **evebox -v -D . --datastore sqlite --input /var/log/suricata/eve.json**
Usage: evebox <command> [options]

Commands:
    server          Start the EveBox server
    agent           Start the EveBox agent
    config          Server configuration tool
    version         Print the EveBox version
    esimport        Run the Elastic Search Eve import tool
    evereader       Run the Eve log reader tool
    oneshot         Run one time with an eve.json file
    gencert         Generate TLS certificate

root@suricata:/etc# 
***************

I was fortunate enought to get Evebox running using oneshot option, but the web user interface is not accessible from separate computer e.g. http://192.168.1.1:5636/ from 192.168.1.10. Possibly some web server is also needed? Are there any complete installation guide to install Evebox onto Web server?

2020-07-02 16:16:53 (oneshot.go:241) <Info> -- /var/log/suricata/eve.json: 2905 events (98%)
2020-07-02 16:16:53 (oneshot.go:241) <Info> -- /var/log/suricata/eve.json: 2964 events (99%)
2020-07-02 16:16:53 (oneshot.go:241) <Info> -- /var/log/suricata/eve.json: 3007 events (100%)
2020-07-02 16:16:53 (oneshot.go:285) <Info> -- Starting server.
2020-07-02 16:16:53 (server.go:131) <Info> -- Session reaper started
2020-07-02 16:16:53 (server.go:165) <Info> -- Authentication disabled.
2020-07-02 16:16:53 (server.go:261) <Info> -- Listening on [127.0.0.1]:5636
2020-07-02 16:16:53 (oneshot.go:333) <Info> -- Bound to port 5636
2020-07-02 16:16:53 (oneshot.go:337) <Info> -- Attempting to start browser.

If your browser didn't open, go to http://localhost:5636

** Press CTRL-C to exit and cleanup.. ** 

I have also applied a firewall rules for the port 5636, but still no access to the web interface;
iptables -I INPUT -p tcp --dport 5636 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -I OUTPUT -p tcp --sport 5636 -m conntrack --ctstate ESTABLISHED -j ACCEPT 
iptables -I INPUT -p udp --dport 5636 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -I OUTPUT -p udp --sport 5636 -m conntrack --ctstate ESTABLISHED -j ACCEPT

**Comment by jasonish** [comment]
> root@suricata:/etc# **evebox -v -D . --datastore sqlite --input /var/log/suricata/eve.json**

Here you should try:
```
evebox server -v -D . --datastore sqlite --input /var/log/suricata/eve.json
```
(note "server")

As for connecting with a browser.  By default, EveBox only binds to localhost.  To open that up you'll also need to add `--host 0.0.0.0` to the command line.

**Comment by beamzer** [comment]
Sorry to tail on this question, but is it possible to use the dockerized version with SQLite (so without the elastic search server)?
I use suricata locally on pcaps, so that generates small eve.json files and it would be nice to view them that wat.

thanks in advance,
Ewald....

**Comment by jasonish** [comment]
I'm going to use the master branch as I plan to release that very soon.  But you could do something like:
```
docker run -p 5636:5636 --rm -it -v $(pwd)/data:/data:z -v /var/log/suricata/eve.json:/var/log/suricata/eve.json:z jasonish/evebox:master evebox server --host 0.0.0.0 --database sqlite -D /data --input /var/log/suricata/eve.json
```

Not that the evebox binary is a single static executable.  Depend on how long you need the database around, maybe oneshot mode would work for you?
```
evebox oneshot /path/to/eve.json
```

That will work in Docker soon, but as it only binds to localhost, and no option to change that in oneshot mode, you can't connect to it in Docker.  I will make a change soon so you can access it in Docker. It would then look something like:
```
docker run -p 5636:5636 --rm -it -v /var/log/suricata/eve.json:/var/log/suricata/eve.json:z jasonish/evebox:master evebox oneshot --host 0.0.0.0 /var/log/suricata/eve.json
```

**Comment by beamzer** [comment]
Hi Jason,
that
```
docker run -p 5636:5636 --rm -it -v $(pwd)/data:/data:z -v /var/log/suricata/eve.json:/var/log/suricata/eve.json:z jasonish/evebox:master evebox server --host 0.0.0.0 --database sqlite -D /data --input /var/log/suricata/eve.json
```
worked! Thanks for helping me out!
Ewald....
