### ISSUE TITLE
Evebox integration with suricata

### ISSUE THREAD

**Issue by PRAYA62** [jasonish/evebox#139]
I have setup suricata and logs are processing to eve.json. I have installed evebox on same server.
I want to access evebox on the browser to visualize eve.joson logs.
What and all configurations need to do in order to achieve this?

**Comment by jasonish** [comment]
By default it binds to localhost as there is no authentication or TLS setup by default either.  You can use `--host 0.0.0.0` to access it from another machine.

Support for basic authentication is covered here: https://evebox.readthedocs.io/en/latest/authentication.html

**Comment by jasonish** [comment]
Closing. Please re-open/comment if you still have issues.
