### ISSUE TITLE
Not all alerts are presented on Inbox and Alerts Tab

### ISSUE THREAD

**Issue by cocotte42** [jasonish/evebox#141]
Hi,

I have a strange issue :
I have only a little part of my alerts presented on <Inbox> and <Alerts> Tabs.
If I filter on "last minute, last hour, all", it respect the filter (not presenting alerts outsite of the filter) but always only a part of alerts (perhaps 3 or 5 instead of 20/30) 
If I use "Events tab" and then filter "Event-type" to Alerts : I got all my alerts !

Another strange thing, even if I see only 3 alerts on Inbox, if I "select all" then "archive", **all** my alerts are archived (not only the 3 I saw on Inbox).

The issue seems to be related to elasticsearch. If I use mysql, no problem. But it's not related to the insertion method to elasticsearch, I got same issue when populate from evebox and logstash.

Regards.

**Comment by jasonish** [comment]
Can you tell me the version of Elasticsearch and Evebox?

Thanks.

**Comment by cocotte42** [comment]
Evebox : 0.11.1 (from official repository of debian stable)
elasticsearch : 7.8.0 (last from elastic repository)
I make a chek this morning, and there are 36 alerts in inbox, but about 300 alerts not archives in events tab.

**Comment by jasonish** [comment]
I wonder if you are just seeing the aggregation that occurs in the Inbox view.  Under the "Events" tab you see each individual event record. In the "Inbox" tab you also see alerts which are grouped by signature_id/src_ip/dest_ip with a count of the number of alerts per that group.

**Comment by cocotte42** [comment]
Doh ! You are right !
I use evebox since about since about 2 years and never seen that before. So sorry !! 
Thanks for your quick responses and for your work en evebox ;o)

**Comment by jasonish** [comment]
No worries. Glad to help.
