### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ngms17** [jasonish/evebox#150]
I am having this error while starting evebox server.

<img width="794" alt="Screenshot 2020-12-03 at 10 27 26" src="https://user-images.githubusercontent.com/19928515/100997544-479d1780-3552-11eb-8e1b-d7cd9219dd70.png">

**Comment by jasonish** [comment]
How are you adding your events to Elasticsearch?

**Comment by ngms17** [comment]
Filebeat -> Logstash -> Elastic

But my index is not the logstash default

**Comment by jasonish** [comment]
You will have to tell EveBox the name of your index prefix.  So by default it assumes "logstash-*", the `--index` can change that. However, EveBox only works against the default Logstash schema, so if you remap fields, or change the types, etc. Its unlikely to work.

It also doesn't work against ECS if using the Filebeat Suricata module. I'm working on that though.

**Comment by jasonish** [comment]
I think that has been resolved. If an ECS issue, follow here: https://github.com/jasonish/evebox/issues/97
