### ISSUE TITLE
Spinning wheel for inbox with current docker image.

### ISSUE THREAD

**Issue by banjoey** [jasonish/evebox#16]
After following the directions for starting up the container, I get the giant spinning wheel of gray balls. I'm using build bauhyagtfhhiu5mqks35vvr, from 2016-07-28T15:13:59.828Z.

I've tried to get more details but do not see anywhere that logs are being generated. When I log into the running container with sh, I can perform a wget on our elasticsearch server at port 9200, and netstat shows an active connection.

Is there another location inside the container where I might be able to get additional logs to help troubleshoot?

**Comment by jasonish** [comment]
The only logs are printed out to stderr, but for a large part the backend is just a proxy to elastic search, which means much of the error logging will happen in the browser console?  Are you able to enable the developer/web console on firefox or chrome and see what is displayed?  Intercepting errors in the browser and putting them into a UI element has been a long running todo for me, but for now the developer console in the browser is your best bet.

**Comment by banjoey** [comment]
OK, great! Found the problem. we aren't using logstash-* for our ids records index. Is this configurable via a -e parameter per chance? Can I pass that in with a -e like with ELASTICSEARCH_URL?

**Comment by jasonish** [comment]
Does your index follow the logstash-* pattern?  As in someindex-<data>?

**Comment by banjoey** [comment]
Yes. we have hourly indexes. For now it's json-* but we'll likely start piping all our ids data to ids-* at some point.

**Comment by jasonish** [comment]
Ok, try the new version (just docker pull it or however you originally got it).  It has a -i option on the backend to specify the index (-i "json-*").  Travis-CI that automatically builds the packages spewed a bunch of errors but the build appears to work.  Just checking now to see if it was a travis side thing.

**Comment by banjoey** [comment]
SWEET!!!

Works like a charm. Many thanks for your help.
