### ISSUE TITLE
EveBox may start before Elasticsearch is ready when started from systemd

### ISSUE THREAD

**Issue by fcorneli** [jasonish/evebox#170]
Running Evebox as systemd service on CentOS, with elasticsearch as database, gives me an error that elasticsearch is not available upon system reboot and hence the Evebox service fails to start.
Adding to `/usr/lib/systemd/system/evebox.service` the following line under `[Unit]` solves the issue:
```
After=elasticsearch.service
```
Maybe this could be included per default?

**Comment by jasonish** [comment]
Not all systemd users of EveBox are using Elasticsearch.  I'll have to tune the waiting for elasticsearch to become available behaviour.

**Comment by fcorneli** [comment]
> Not all systemd users of EveBox are using Elasticsearch.

That's why I used `After` instead of `Requires`. Hence if Elasticsearch runs on the machine, Evebox will be started after Elasticsearch (just in case Evebox actually uses Elasticsearch as data source). If Elasticsearch does not run on the machine, Evebox will also be started and `After` is simply not used by systemd.

But indeed, ideally Evebox can survive the fact that Elasticsearch is started after it.

**Comment by jasonish** [comment]
EveBox will now wait on startup for Elasticsearch to be ready. This was needed even outside of systemd.  This is now in release development builds.  I plan a release build soon I think.
