### ISSUE TITLE
Docker ARM

### ISSUE THREAD

**Issue by Robs68** [jasonish/evebox#171]
Hi,

Is-it possible to have a docker file compatible with armv8 plz ? 

`latest: Pulling from jasonish/evebox`
`no matching manifest for linux/arm64/v8 in the manifest list entries`

Thanks

Robs

**Comment by jasonish** [comment]
Yes. Will do so in the next day or so.

**Comment by Robs68** [comment]
Cool thanks :)

**Comment by jasonish** [comment]
Can you do me a faviour and try:
```
docker pull jasonish/evebox:master
docker run jasonish/evebox:master evebox version
```
I don't have arm64 handy to test on. Thanks.

**Comment by jasonish** [comment]
Great.  Thanks. I've applied this to the latest release version as well, so no need to stick with master.
