### ISSUE TITLE
[CLI] Adding users - parameters are not honored

### ISSUE THREAD

**Issue by thereisnotime** [jasonish/evebox#173]
There should be a check if -u/-p length is bigger than 0 before printing "Username:" when declaring the variable here: https://github.com/jasonish/evebox/blob/efeabc07d7a5274a0094501ff17a9fb556121c4d/src/commands/config/users.rs#L110

Otherwise this blocks automation like so:
https://i.imgur.com/34mI4ME.png

**Comment by jasonish** [comment]
Thanks. Will fix this in the next few days.

**Comment by jasonish** [comment]
Fixed in master branch. New development builds will be uploaded shortly.
