### ISSUE TITLE
per ip address report

### ISSUE THREAD

**Issue by inliniac** [jasonish/evebox#19]
I think it could be interesting to have a per IP address report that collects all records for that IP.

e.g.
user agents it used in outgoing http
tls versions it used for outgoing connections

number of flows to and from the ip
bytes/packets from netflows
top alerts/http/tls/dns

dns name(s) that returned this IP
tls sni in incoming to this ip
http hostname incoming to this ip

**Comment by jasonish** [comment]
Thumbs ip, means I agree.

**Comment by jasonish** [comment]
Item break down:
- [ ] Outgoing HTTP user agents
- [ ] Incoming and outgoing TLS versions.
- [ ] Number of flows to (where IP is server) and from (where IP is client) IP
- [ ] Bytes to and from IP.
- [ ] Packets to and from IP.
- [ ] Top alert
- [ ] Top HTTP (probably by hostname).
- [ ] Top TLS (probably by CN)
- [ ] Top TLS SNI (by SNI)
- [ ] Top requested DNS host names.
- [ ] Incoming HTTP hostnames.
- [ ] Incoming SNI names.

**Comment by jasonish** [comment]
Finally added packet counts (http://www.clipular.com/c/4510211515875328.png?k=nx38i1HSqCsBpGbafmc5XqYgcqo) so I can close this off. Future enhancements or issues should get their own issue.  Thanks.
