### ISSUE TITLE
How to encrypt password

### ISSUE THREAD

**Issue by ngms17** [jasonish/evebox#201]
How can i cypher the password field to avoid being in clear text?

database:
  elasticsearch:
    username: username
    password: password

**Comment by jasonish** [comment]
This is a problem I'm not sure how to best solve.  If it was encrypted, you would have to enter a password everything you started EveBox which is not ideal.  I think the common way for client side applications to do this is configuration files that you limit the permissions on. Postfix is like this for configuration credentials against your relay SMTP servers.  I suppose I could an an option where credentials were looked for in another file like Postfix does, but it you'd still be relying on the filesystem to protect your credentials.

Another option is to take allow the username and password to be set as an environment variable (this might work, I need to test), then you could integrate with tools like Hashicorp Vault.

**Comment by jasonish** [comment]
Closing as out of scope.  Filebeat, and lots of other tools have this same issue and generally file system permissions are the way.
