### ISSUE TITLE
error when adding repository

### ISSUE THREAD

**Issue by kdy1968** [jasonish/evebox#203]
root:~# wget -vO - https://evebox.org/files/GPG-KEY-evebox | sudo apt-key add -
--2022-03-13 07:25:04--  https://evebox.org/files/GPG-KEY-evebox
Resolving evebox.org (evebox.org)... 172.105.5.173
Connecting to evebox.org (evebox.org)|172.105.5.173|:443... connected.
ERROR: The certificate of ‘evebox.org’ is not trusted.
ERROR: The certificate of ‘evebox.org’ has expired.
gpg: no valid OpenPGP data found.

temporarily resolved by using..
deb [trusted=yes] http://evebox.org/files/debian stable main

i proballly wouldnt leave it as trusted...

**Comment by jasonish** [comment]
Is the date on your machine correct? The cert doesn't expire for another 4 days. With that, I need to renew it anyways.
