### ISSUE TITLE
How to get GeoIP information on evebox

### ISSUE THREAD

**Issue by ngms17** [jasonish/evebox#225]
How can i get evebox to show me the GeoIP section when i look into a event/alert log?

I already have the geoIP databases on my server.

Thank you.

**Comment by jasonish** [comment]
How are you adding events to your database?

**Comment by vvperedery** [comment]
I have the same question. I am using Suricata and ELK. NO Filebeat

**Comment by ngms17** [comment]
Hi am sending the logs to ES via Filebeat (Suricata module) and i am running evebox server against my ES host to fetch the events

**Comment by jasonish** [comment]
GeoIP data should be added by the log processor. So in these cases either Logstash or Filebeat.

If the geoip is being added, but just not being displayed by EveBox, send me an event sample in JSON and I'll take a look.

**Comment by ngms17** [comment]
How can i send it to you on private?

**Comment by vvperedery** [comment]
![Снимок экрана 2022-10-25 164107](https://user-images.githubusercontent.com/116342390/197789726-76049c65-3165-4a3b-8eee-d63db38a5e07.png)
I'm talking about this panel in evebox. How to make it work?

**Comment by jasonish** [comment]
> How can i send it to you on private?

My email should be visible on my GitHub profile if you want to verify, but email to ish@unx.ca works.

**Comment by ngms17** [comment]
Any news?

**Comment by jasonish** [comment]
> Any news?

Not really.  I have ECS events now in my Elastic and see the geo ip..  Won't be hard to add now.  Next week or 2 as I'm travelling this week.

**Comment by jasonish** [comment]
Looking at something like this for ECS provided GeoIP...
![Screenshot from 2022-11-03 17-46-37](https://user-images.githubusercontent.com/644115/199849528-697f9e3c-ad93-4c99-a7af-f9f23399eba1.png)

**Comment by ngms17** [comment]
Thank you! Seems perfect. Waiting for any updates

**Comment by jasonish** [comment]
You can give the latest development build a try: https://evebox.org/files/development/
