### ISSUE TITLE
Question about the user authentication

### ISSUE THREAD

**Issue by kun135** [jasonish/evebox#227]
Hi，
  I found that the user authentication function does not work，I can login with any user，Is it a problem with my configuration?

![image](https://user-images.githubusercontent.com/117283319/200245297-e43cb738-0e2a-4955-98e6-e653157eaa18.png)
![image](https://user-images.githubusercontent.com/117283319/200247921-dd0a6c45-d435-4c52-8903-3a5f9e1e3344.png)
![image](https://user-images.githubusercontent.com/117283319/200245623-113bddbd-4c18-417a-9a12-44c241d8f760.png)

My configuration is as follows:

```
authentication:
  required: true
  type: usernamepassword
```
My user configuration information is as follows

```
 evebox config -D /var/lib/evebox/ users list
2022-11-02 21:02:41  INFO refinery_core::traits: current version: 1    
2022-11-02 21:02:41  INFO refinery_core::traits::sync: no migrations to apply    
{"uuid":"14e5189a-bd7e-4e31-a340-561226419579","username":"xukun"}
```

My evebox service information is as follows：

```
service evebox status -l
[root@Network-Security-Suricata bin]# service evebox status                       
Redirecting to /bin/systemctl status evebox.service
● evebox.service - Evebox Server
   Loaded: loaded (/usr/lib/systemd/system/evebox.service; disabled; vendor preset: disabled)
   Active: active (running) since 一 2022-11-07 15:00:47 CST; 4min 58s ago
 Main PID: 8592 (evebox)
   CGroup: /system.slice/evebox.service
           └─8592 /usr/bin/evebox server -c /etc/evebox/evebox.yaml --host 10.190.122.14 -v

```

At present i found that only version 0.15.0 has this problem.

At the same time, I found that pcap(https://127.0.0.1:5636/api/1/eve2pcap) always prompts  401 authentication required
![image](https://user-images.githubusercontent.com/117283319/200246437-7a10c0db-1e5b-46a0-836e-050caf380553.png)
![image](https://user-images.githubusercontent.com/117283319/200246604-47f1d529-47ef-48ef-bb75-81c98b4c628f.png)
![image](https://user-images.githubusercontent.com/117283319/200246670-a006783f-e3af-47ec-9f07-1788fb32c190.png)
The error message is as follows
```
journalctl -u evebox -f
11月 07 15:11:02 Network-Security-Suricata evebox[8592]: 2022-11-07 15:11:02  INFO evebox::server::main: Authentication required but not session found.
```

How should I fix this problem？ Thank you very much！

**Comment by kun135** [comment]
My evebox service information is as follows：
---------------------------
service evebox status -l
Redirecting to /bin/systemctl status  -l evebox.service
● evebox.service - EveBox Server
   Loaded: loaded (/usr/lib/systemd/system/evebox.service; disabled; vendor preset: disabled)
   Active: active (running) since 三 2022-11-02 21:27:49 CST; 11s ago
 Main PID: 42392 (evebox)
    Tasks: 97
   CGroup: /system.slice/evebox.service
           └─42392 /usr/bin/evebox server -c /etc/evebox/evebox.yaml -v --host 127.0.0.1 -D /var/lib/evebox/. --datastore sqlite --input /var/log/suricata/eve.json
---------------------------
Thank you very much！

**Comment by kun135** [comment]
At present i found that only version 0.15.0 has this problem.

**Comment by jasonish** [comment]
Sorry for the late response. Will look at this in the coming week.

**Comment by kun135** [comment]
It's alright, thank you very much.

**Comment by kun135** [comment]
It's alright, thank you very much.

**Comment by kun135** [comment]
It's alright, Thank you very much.

**Comment by jasonish** [comment]
Confirmed, embarrassed.  Will have a fix + release this week.

**Comment by jasonish** [comment]
Fixed in git main.  Will be in 0.16.0 soon.
