### ISSUE TITLE
if authentication request true in yaml, How to do for api?

### ISSUE THREAD

**Issue by jianvector** [jasonish/evebox#230]
Hello:

if in yaml config:

authentication:
  required: true
  type: usernamepassword

when curl get api:
curl -G http://2.2.2.1:5636/api/1/alerts -d time_range=84600s
{"error":"authentication required","status":401}

How to do it ?

Thanks

**Comment by jasonish** [comment]
`curl -u USERNAME:PASSWORD ...` will work.

**Comment by jianvector** [comment]
> `curl -u USERNAME:PASSWORD ...` will work.
I tested for it.
This is Suitable for basic authorization, invalid for evebox.

**Comment by jasonish** [comment]
> > `curl -u USERNAME:PASSWORD ...` will work.
> > I tested for it.
> > This is Suitable for basic authorization, invalid for evebox.

Are you saying it doesn't work? Or its not an ideal authentication method for API usage?

**Comment by jianvector** [comment]
it doesn't work.
I think ideal authentication: apikey
go example for client to get data:
    req, err := http.NewRequest("GET", url, nil)

    req.Header.Add("Authorization", apiKey)
    req.Header.Add("Accept", "application/json")
    req.Header.Add("Content-Type", "application/json")

    resp, err := client.Do(req)

**Comment by jasonish** [comment]
I fixed basic http authentication, so you can use this.  In my opinion, basic authentication is just as secure as simple API key based authentication, so I'll stick with that for now until there is a need for proper API key based authentication, with a secret, and an hmac, etc.
