### ISSUE TITLE
Consider adding community flow ID so you can easily pivot to other tools. 

### ISSUE THREAD

**Issue by Obsecurus** [jasonish/evebox#235]
The Suricata community flowID is a respected industry method for pivoting across tools. It would be really nice if evebox capture this in the ElasticSearch index and UI. 

https://github.com/corelight/community-id-spec

https://suricata.readthedocs.io/en/suricata-4.1.2/output/eve/eve-json-output.html#community-flow-id

**Comment by jasonish** [comment]
Do you have any more detail on how you would like to see community ID added?  Simply I could add it to the event view, below the existing "Flow ID" which makes sense.

Its still on the administrator of Suricata to enable it though.

**Comment by jasonish** [comment]
Added to view and handling pivot by community_id.
