### ISSUE TITLE
alerts report should show full range

### ISSUE THREAD

**Issue by regit** [jasonish/evebox#24]
If I ask an alert report for 1 hour and I only have 2 alerts in the interval, I have something which is displayed like the following screenshot:

![screenshot from 2016-09-02 22-44-12](https://cloud.githubusercontent.com/assets/308616/18217778/087b5280-715f-11e6-94d7-b7fa0a8b3500.png)

It would be better to display the full 1h range.

**Comment by jasonish** [comment]
I think this has something to do with the time bracketing of either Elastic Search or the Mozilla Metrics library.  I think a quick fix might be to bucket by the minute in a 1 hour report instead of by the hour.

**Comment by jasonish** [comment]
Should be fixed now, used the Elastic Search extended_bounds as documented here:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-histogram-aggregation.html#search-aggregations-bucket-histogram-aggregation-extended-bounds
