### ISSUE TITLE
Report graph fails to refresh

### ISSUE THREAD

**Issue by PogCarr** [jasonish/evebox#247]
When looking at the Evebox reports and it is showing existing alerts over time, if you change the timeframe to something that has no alerts (say the last minute) while the boxes refresh and indicate "No data", the graph continues to display the alerts over time from the previous timeframe.
![image](https://user-images.githubusercontent.com/4399486/217865339-43cd0b07-03a3-43af-a9b3-19e4fc916e59.png)

**Comment by jasonish** [comment]
Thanks for the report.  I've fixed this in my dev branch so going to mark as closed for now, but will be fixed in the next release.
