### ISSUE TITLE
Implement authentication

### ISSUE THREAD

**Issue by SleuthKid** [jasonish/evebox#25]
For the long run it might be necessary to implement a session handler in the go API to handle authentication with basic user and group management.

There are some go packages that might help:
https://github.com/avelino/awesome-go#authentication--oauth

I will try to figure out the most elegant way to do this and could be working on the Go part.

**Comment by jasonish** [comment]
Auth is on the todo list, for the most simple case I can pull it in from my other Go project, https://github.com/jasonish/dumpy, but as EveBox doesn't have a mandatory configuration file yet, I'm not sure where to store the info.

I could do an .htpasswd like file, or finally embed a database that could hold the auth info.  I do not want to store it in Elastic Search, at least not until I've moved the data access layer to Go from JavaScript as I do plan to support at least one alternate database.

**Comment by SleuthKid** [comment]
I think it could be a good idea to use a pure go data backend like bolt db:
https://github.com/boltdb/bolt

**Comment by jasonish** [comment]
I guess I should ask, what are your requirements for auth?  I have 2 other schemes I may need to support, neither of which are basic auth backed by an .htpasswd file or a database, which is one I need to do as well, as it will probably be the most common.

The other 2 I'm looking at are pre-auth with a reverse proxy, and external auth where I spawn a process.

**Comment by jasonish** [comment]
I've thought about this some more and I think I'll be using BoltDB for authentication.  I think its a good idea to separate the Evebox "internals" data store from the event data store.

**Comment by jasonish** [comment]
Git master now has authentication and will be included in the next release.

Authentication is implemented using a "configuration database", an SQLite database that holds users for now, but will probably grow to hold more non-event data. Users are added with a command line tool, though I would like to add full GUI support for user management.

Optionally, GitHub can be used for authentication, but the user first needs to be created.

No roles yet, but they'll come when when features exist they make sense for.
