### ISSUE TITLE
auto reloading temporary makes archived events reappear

### ISSUE THREAD

**Issue by inliniac** [jasonish/evebox#26]
My server is slow, and when archiving a lot of events Evebox works on it for a while. Think about 30 to 60 seconds. During this time the auto refresh shows my recently archived events again. When Evebox processed all events the next refresh hides them again.

**Comment by jasonish** [comment]
Probably best to just not auto refresh if there are elasticsearch operations in progress. Will fix this up real soon.

**Comment by inliniac** [comment]
Sounds like a good solution.

**Comment by SleuthKid** [comment]
You might be able to speed up the archiving process for a lot of selected items by doing a bulk update instead of using a single post to ES for each item.

**Comment by jasonish** [comment]
> You might be able to speed up the archiving process for a lot of selected items by doing a bulk update instead of using a single post to ES for each item.

Updates are done in batches of up to 1000, but only for the same event (sig id, src, dst).  But up 16 bulk operations can be happening concurrently.  We could collate different events into the same bulk request, but that would get tricky with minimal gain I think as we still have to request a batch events, submit the patch of events, search, etc...  Its just not pretty with ES.

There is a new update by query API, but its still experimental, and even then requires the user to turn on scripting support (not on by default).  Perhaps when its no longer experimental I'll take a look at it.

**Comment by jasonish** [comment]
Fixed with da3e7ab768ad34a2eafee6c0c163fd53f79d7ef3
