### ISSUE TITLE
Logs not appearing after ES upgrade to version 8.6.2

### ISSUE THREAD

**Issue by ngms17** [jasonish/evebox#265]
After upgrading to ELK version 8.6.2, Evebox does not show any events on the web frontend and it gives the the following warning:

```
Mar 29 14:50:46  evebox[268112]: 2023-03-29 14:50:46  WARN evebox::elastic::eventrepo: Elasticsearch response has no aggregations
Mar 29 14:50:47  evebox[268112]: 2023-03-29 14:50:47  WARN evebox::elastic::eventrepo: Elasticsearch response has no aggregations


```

**Comment by ngms17** [comment]
Found the solution. Has i am using data-streams, add to use `index: name-of-index*` and not `index: name-of-index-*`

**Comment by jasonish** [comment]
Can I ask how you are adding events to a datastream? Using Filebeat with the Suricata module, or something else? Thanks!
