### ISSUE TITLE
evebox server cannot start without users

### ISSUE THREAD

**Issue by fcorneli** [jasonish/evebox#267]
When trying to start `evebox` server without any user, you get the following error:
```
ERROR evebox: Username/password authentication is required, but no users exist
```
and the process terminated (RPM), which also causes the `evebox-agent` to start complaining that it cannot connect.
This should not happen I guess. `evebox` server should be able to start without portal users configured.

**Comment by jasonish** [comment]
Thanks. Updated to just log a warning instead.
