### ISSUE TITLE
de-escalate issue

### ISSUE THREAD

**Issue by inliniac** [jasonish/evebox#27]
Go to escalated view. Click on an escalated event. Click 'de-escalate'. Click 'back'. We are again in the escalated view. The 'un-escalated' event is still visible. It's star isn't solid though, and after a refresh the event is gone.

**Comment by jasonish** [comment]
Funny, I think I did it this way on purpose, but can't remember why.  Yeah, I agree it would be better if it was gone from the list.

I also think that "De-escalate" should take you back as well, like hitting "Archive" does.
