### ISSUE TITLE
Comment functionality removed in 0.17 ?

### ISSUE THREAD

**Issue by shoenix** [jasonish/evebox#271]
Today I wanted to annotate an escalated event by adding a comment, but it seems this functionality had disappeared ? I used this in 0.16 and below, but I cannot find anything related in the changelog, or am I looking in the wrong place ? I'm running against Elasticsearch.

**Comment by jasonish** [comment]
Yes, sorry about this. Got dropped, from the frontend only while migrating libraries.  I'll bring it back as it all the support is still there on the backend.

**Comment by shoenix** [comment]
Jason, thanks for the confirmation. I really use this to annotate escalated events so I can archive and use them in report generation monthly. This gives an overview and history on investigated events and origin. I did see the overhaul of the event screen itself, which is much better in 0.17 as it contains a better overview of the available data. 

I'll keep an eye out when this is brought back.

**Comment by jasonish** [comment]
I'm traveling all next week so it probably won't be til the week after. Anyways, this feedback is very valuable as I had always questioned, the value of comments and just thought they always got lost.  I'd be curious to know if you had more thoughts on how to make them better.

**Comment by shoenix** [comment]
Jason, no hurries. I reverted back to 0.16 for now since we got audited and I had to show them how I manage and track the incoming events. I would love to give more ideas on how to make this better. Do you want to have this here, or would you like me to send my ideas via mail ?

**Comment by jasonish** [comment]
Fixed, will be in 0.19.0.
