### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by jianvector** [jasonish/evebox#273]
I have login error with below:
Login failed: {"headers":{"normalizedNames":{},"lazyUpdate":null,"headers":{}},"status":0,"statusText":"Unknown Error","url":"/api/1/login","ok":false,"name":"HttpErrorResponse","message":"Http failure response for /api/1/login: 0 Unknown Error","error":{"isTrusted":true}}

but restart evebox , no error for that, login success.

**Comment by jasonish** [comment]
Please let me know if this is still an issue.  Authentication is now enabled by default, so its been through more testing.
