### ISSUE TITLE
Unable to negate a phrase in the query string

### ISSUE THREAD

**Issue by jasonish** [jasonish/evebox#275]
For example, "NOT ET INFO", or !"ET INFO", doesn't do what you might expect it to.

**Comment by malexe3169** [comment]
is there a workaround, to filter out a query string?

**Comment by jasonish** [comment]
No, but have fix nearly done that should work with Elasticsearch and SQLite. It lets me create a query like:
```
dns -"et info" -"et dns"
```
to match all events containing `dns`, but exclude all those `et info` or `et dns`.
