### ISSUE TITLE
per subnet report

### ISSUE THREAD

**Issue by inliniac** [jasonish/evebox#28]
Pretty much the same report as in #19, but then applied to a subnet. For me it would be fine if it's not exactly a subnet, but something like "192.168.1.*" or simply "192.168.1"

**Comment by jasonish** [comment]
So you can try out a quick hack I've added for now..  Go to an IP report, then in the URL bar remove the last component, but leave the ".".  For example "192.168.1.".  If the IP ends in a "." it'll do a prefix query.

Real CIDR queries are hard with elastic search.  It can do them if the field is analyzed as an IP address, but if its analyzed as an IP address, IPv6 address will cause index errors.  So I don't think its going to get better than this with ES.

Postgres could be a different story, with proper support for v4 and v6 IP addresses.

Any ideas on how to pivot to such a "network" report?

**Comment by jasonish** [comment]
On an IP report, see the "Related" link in the top right.

**Comment by jasonish** [comment]
Closing for now. I think the related searches can deal with this somewhat. Or as best we can with Elastic Search which may have some CIDR support for IPv4, but not for IPv6.
