### ISSUE TITLE
No alert showing in Inbox nor Alert

### ISSUE THREAD

**Issue by elhijo** [jasonish/evebox#29]
Hi,

I've used evebox for a few weeks with ease and since this morning, I have no more alerts rising in Inbox nor Alert tabs.

If I choose "Event type:alert" in Events tab I can see some alerts, I also can find alert in kibana if filtering on event_type:alert

I've updated evebox to last version (This is EveBox version 0.6.0dev (Rev: dc36c6a). )

I think it might be linked to the fact that I've changed the elasticsearch server to a new computer today, but as there's no configuration file, I don't know where to look at.

Thanks for your help.

**Comment by jasonish** [comment]
On Tue, Oct 4, 2016 at 11:04 AM, elhijo <notifications@github.com> wrote:

> Hi,
>
> I've used evebox for a few weeks with ease and since this morning, I have
> no more alerts rising in Inbox nor Alert tabs.
>
> If I choose "Event type:alert" in Events tab I can see some alerts, I also
> can find alert in kibana if filtering on event_type:alert
>
> I've updated evebox to last version (This is EveBox version 0.6.0dev (Rev:
> dc36c6a
> <https://github.com/jasonish/evebox/commit/dc36c6a623373b7055ad9c6e2290332b17280e17>).
> )
>
> I think it might be linked to the fact that I've changed the elasticsearch
> server to a new computer today, but as there's no configuration file, I
> don't know where to look at.
>
Did you update the "-e" parameter to point EveBox at the new Elastic Search
IP or hostname?

**Comment by elhijo** [comment]
Yes I as told you I can see alert if I go in the Events tab and select "event type: alert"

**Comment by jasonish** [comment]
I've seen this when logstash templates don't get loaded properly.  Or if Elastic Search gets upgraded, then it takes up to a day for Logstash to create the new index.

Are you using Logstash?  The problem is that the template is not respected sometime.  I'm not sure how to reforce a template to be loaded yet.

**Comment by elhijo** [comment]
Yes I'm using logstash, I'll have a look at this way and keep you updated.
Thanks

**Comment by jasonish** [comment]
I know I've had luck deleting the current index and restarting logstash.  Its a bit brute force, but other than the query DSL, I don't know a whole lot about it.

**Comment by elhijo** [comment]
Hi,

I'm a bit disappointed, I've destroyed my elasticsearch index (ELK+Evebox still under testing, Snorby is slow but works well) but it still the same.

I'm ok to reinstall everything from scratch, but I'm not sure that's the best way to understand what's happening.

Any other idea on your side ?

Thanks

**Comment by jasonish** [comment]
What version of Elastic Search and Logstash are you using?

**Comment by elhijo** [comment]
logstash-2.3.4-1
elasticsearch-2.3.5-1

**Comment by jasonish** [comment]
I'm not sure what to suggest right now.  I just tried the following on a fresh CentOS 7 virtual machine:
- Installed OpenJDK 1.8 with yum.
- Installed the Elastic Search 2.3.5-1 RPM
  - Then: `systemctl start elasticsearch`
- Installed the Logstash 2.3.4-1 RPM.
- Installed the latest Evebox RPM (https://bintray.com/jasonish/evebox-development-rpm-x86_64/download_file?file_path=evebox-0.6.0-0.20161005064201.x86_64.rpm) - this is newer than what you used but shouldn't make a different.
  - Then `systemctl start evebox`
- Installed the Suricata RPM from EPEL (3.1.2)
  - Put the ET Open rules in /etc/suricata/rules
  - Then `systemctl start suricata`
- Put this logstash config in /etc/logstash/conf.d: https://raw.githubusercontent.com/StamusNetworks/SELKS/master/staging/etc/logstash/conf.d/logstash.conf
  - Note: I commented out the sincedb stuff, I could have just created that directory though.
- Manually started logstash:
  - `/opt/logstash/bin/logstash -f /etc/logstash/conf.d --verbose`

After a few moments went to Evebox, and saw events under the "Events" tab.  Executed a `curl  http://www.testmyids.com` and saw the event in the inbox.

I did this on a Linode VPS, but I don't think that should matter.  If you'd like to take a look around at it, please email me directly at ish@unx.ca and I'll give you access before I shut it down.

**Comment by jasonish** [comment]
Whats your output.elasticsearch section of your logstash.conf look like? Looking into another support issue where the user was using a a custom index name, I found that logstash DOES NOT create a template that matches the configured index name. This results in events showing up in the events tab, but they are not properly analyzed on insert to show up in the searches for the inbox and alerts tab.

So if you are not using an index name of logstash-%{+YYYY.MM.dd} please try doing so.

The alternative is to try EveBox's built in import tool (experimental right).  Using the latest version try something like:
```
evebox import --bookmark -e http://127.0.0.1:9200 --index custom -v /var/log/suricata/eve.json
```

**Comment by elhijo** [comment]
Index name is logstash-%{+YYYY.MM.dd} 
Didn't wanted to reinstall all at a time, so I started by reinstalling logstash and it didn't worked until this morning, suddenly, alerts were back.
So it's now working again...

**Comment by jasonish** [comment]
Yeah, pretty sure its a template issue.  I've seen this happen before, plus have seen it commented on by SELKS users.  I'm adding some tools to eliminate the need for logstash/filebeat to limit the chance of error by those tools.  "esimport" can already reasonably replace Logstash for use with "eve" files.

**Comment by elhijo** [comment]
You're right, Kibana complain about changing index around the same time alert was back.
It seems that index decided to change on it's own, hours after reinstalling logstash...
Well at least it now works.
Thanks for your help

**Comment by infiniteproject** [comment]
I am experiencing the same issue, in a fresh docker setup using this [logstash.conf](https://github.com/StamusNetworks/Amsterdam/blob/master/src/config/logstash/conf.d/logstash.conf) and this [elasticsearch-template.json](https://github.com/StamusNetworks/Amsterdam/blob/master/src/config/logstash/elasticsearch-template.json):

```
 elasticsearch:
    image: elasticsearch:2
    command: -Des.network.bind_host=0.0.0.0 -Des.index.number_of_replicas=0
    volumes:
    - ./data:/usr/share/elasticsearch/data
    environment:
      ES_HEAP_SIZE: 4g
  evebox:
    image: jasonish/evebox
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
    - elasticsearch
  logstash:
    image: logstash:2
    command: /opt/logstash/bin/logstash -f /etc/logstash/conf.d/
    volumes:
    - ./logstash.conf:/etc/logstash/conf.d/logstash.conf:ro
    - ./elasticsearch-template.json:/etc/logstash/elasticsearch-template.json:ro
    - ./logs:/var/log/suricata:ro
    depends_on:
    - elasticsearch
```
Sometimes alerts are displayed in the "alerts" and "inbox" tab, sometimes aren't.

**Comment by jasonish** [comment]
@infiniteproject If you go to the "Events" view (and limit the events to alerts), do you see alerts with the archive button?  Then please confirm that you don't see them in the inbox.

This is a problem that crops up intermittently, often associated with an Elastic Search upgrade, but not always, where queries using aggregates do not return any results.  Still trying to figure out what causes Elastic Search to enter this state.

**Comment by jasonish** [comment]
@infiniteproject If you are in this state, please try restarting just Evebox, if you can and see if it helps.  There actually may be 2 separate issues here.

**Comment by regit** [comment]
@jasonish I've seen the same issue linked with finding if `keyword` or `raw` are used at beginning on evebox run. When elasticsearch was not up at start, evebox was switching to `keyword` causing the non display of alerts.

**Comment by jasonish** [comment]
Ahh, this could explain a few things.  I'm sure last time I ran into this I did a yum update which updated ES and and Evebox.  I think I need to add a periodic ping to handle the case where ES isn't up when Evebox starts.

**Comment by infiniteproject** [comment]
@jasonish @elhijo Yes, I see events and alerts (with event_type:alert and yes, there's the archive button showing) from the events tab. If I docker restart evebox (say a minute after elasticsearch) like @regit pointed out, alerts reappear in the inbox.

**Comment by jasonish** [comment]
@infiniteproject I created a new issue for this, #38 .  Will get to it very soon.

**Comment by torokp** [comment]
Dear jasonish,

I am running evebox on `FreeBSD 11.0-RELEASE-p2`, with evebox version: `0.6.0dev (rev f2202ab)`.
I see all my event in "Events" tab, including the `event_type:alert` ones, but my Inbox and Alerts tab are empty, also the Escaled tab is empty, however I could escalate from the event's subpage. The button "Escalate" turns into "De-escalate" and it remembers, so saving the attribute seems ok.

According to what you wrote above, I tried multiple times dropping whole Elasticsearch instance.
I have tried with Logstash, and also `evebox esimport`.

I have `elasticsearch5-5.0.2`, `kibana50-5.0.2`, `logstash5-5.0.2` versions, installed though pkg.
[evebox_logs.txt](https://github.com/jasonish/evebox/files/691806/evebox_logs.txt)

Thanks for your help and really appreciating your work done with evebox!

**Comment by jasonish** [comment]
@torokp I found an issue that could be the cause of your issues. I'm having an issue deploying the non .deb/.rpm packages to bintray at the moment, but I think it'll work itself out and there should be updated packages within the 1/2 hour.

When starting evebox, check for this line:

2017-01-08 01:25:01 (elasticsearch.go:184) <Info> -- Elastic Search keyword initialized to "raw"

With the new version that should say "keyword" instead of "raw".

**Comment by torokp** [comment]
@jasonish Thanks! I have updated to `0.6.0dev (rev eaa0023) [Sun Jan  8 06:18:31 UTC 2017]`, and now the Inbox, Archive, Escalated **works.**

However it says "raw":
`2017-01-08 07:23:36 (elasticsearch.go:183) <Info> -- Elastic Search keyword initialized to "raw"`

**Comment by jasonish** [comment]
> However it says "raw":
> 2017-01-08 07:23:36 (elasticsearch.go:183) <Info> -- Elastic Search keyword initialized to "raw"

That might be OK.  If using Logstash, your Logstash version will determine that. Logstash 2 will use "raw" (even when used against ES 5), Logstash 5 I believe will use keyword.

The esimport command will do the following:
* If connected to ES 5 and no template exists for the index name provided, it will use the Logstash 5 template (keyword).
* If connected to ES 2 and no template exists for the index name provided, it will use the Logstash 2 template (raw).
* If a template already exists for the index name, esimport will not provide a new one.

This is to be as compatible with Logstash/Kibana as we can be for the time being.
