### ISSUE TITLE
show wrong Timestamp

### ISSUE THREAD

**Issue by StefanSa** [jasonish/evebox#31]
Hi,
have here EveBox version 0.6.0dev (Rev: 1ab8606) and ES 2.4.
EveBox show always the current time but not the alert creation time. 
![evebox_timestamp-01](https://cloud.githubusercontent.com/assets/6105075/19262659/8cd442f6-8f98-11e6-90bf-c801136dbac2.png)

When i look at the details of the alarm, timestamp is missing.
However, in the Json file, this is displayed correctly.
![evebox_timestamp-02](https://cloud.githubusercontent.com/assets/6105075/19262879/9f4049ac-8f99-11e6-8edb-a402ba960f28.png)

thx for any help here.
Stefan

**Comment by jasonish** [comment]
How are you adding events to Elastic Search?  It looks like the eve event is being added as a string instead of json. 






On Tue, Oct 11, 2016 at 2:01 AM -0600, "StefanSa" <notifications@github.com> wrote:












Hi,

have here EveBox version 0.6.0dev (Rev: 1ab8606) and ES 2.4.

EveBox show always the current time but not the alert creation time. 





When i look at the details of the alarm, timestamp is missing.

However, in the Json file, this is displayed correctly.





thx for any help here.

Stefan

**Comment by StefanSa** [comment]
Hi,
>>How are you adding events to Elastic Search?
Suricata-Box (eve.json)  -> rsyslog -> Logger-Box (syslog-ng) -> logstash -> ES
I think this is not the problem.
In Kibana + ES, all events are displayed correctly (also json format).

**Comment by jasonish** [comment]
So if you look at the json of the event here, 

https://evebox.codemonkey.net/#/event/AVeERIQhY0oDrVHoSxJC;referer=%2Fescalated

you will see that the event is actual  JSON under the _source field.  If you look at your event, its not. Instead its is the JSON of the event, but as string in the message field, so individual fields are not being analyzed which is required for all the aggregations that Evebox does for its displays.

**Comment by StefanSa** [comment]
Jason,
For a better overview, i have removed by logstash the _message field, hat is wrong on json?
![evebox_timestamp-03](https://cloud.githubusercontent.com/assets/6105075/19277108/e370b6ae-8fd8-11e6-9654-2bcb757caa56.png)

**Comment by jasonish** [comment]
Any chance that you can bring back the "timestamp" field that exists in a raw "eve" event?

```
{
  "timestamp": "2016-10-11T15:44:47.000155+0000",
  "flow_id": 1591315593695810,
  "event_type": "flow",
  "src_ip": "190.153.251.218",
  "src_port": 3845,
  "dest_ip": "50.116.50.93",
  "dest_port": 445,
  "proto": "TCP",
  "flow": {
    "pkts_toserver": 3,
    "pkts_toclient": 3,
    "bytes_toserver": 186,
    "bytes_toclient": 162,
    "start": "2016-10-11T15:43:44.463426+0000",
    "end": "2016-10-11T15:43:45.660132+0000",
    "age": 1,
    "state": "closed",
    "reason": "timeout"
  },
  "tcp": {
    "tcp_flags": "16",
    "tcp_flags_ts": "02",
    "tcp_flags_tc": "14",
    "syn": true,
    "rst": true,
    "ack": true,
    "state": "closed"
  }
}
```

Evebox uses this field in some cases for sorting due to its higher precision than the "@timestamp" field.

**Comment by StefanSa** [comment]
OK, i found the reason. Eve Box looks up "timestamp" and not to "@timestamp" to find the date.

**Comment by StefanSa** [comment]
Jason,
after 24h test, i can confirm that If "timestamp" is missing, EveBox does not recognize the date.
Please revisit your fallback handling from "timestamp" (if missing)  and to "@timestamp".

**Comment by jasonish** [comment]
The timestamp is used in quite a few places.  I would rather people make sure not to remove a critical piece of the "eve" event.  @timestamp is not a suitable replacement, due to the lack of precision.

**Comment by jasonish** [comment]
Closing on the basis that "timestamp" is a key part of an Eve event and that "@timestamp" is Elastic Search metadata, and that database support for something other than ES is planned.
