### ISSUE TITLE
Archive function does not work

### ISSUE THREAD

**Issue by StefanSa** [jasonish/evebox#32]
On EveBox version 0.6.0dev (Rev: 1ab8606) and ES 2.4, Archive function does not work.
If i archive a single event, this is displayed again in the Inbox / Alerts after the refresh.

Perhaps a problem with the time stamp:
[show wrong Timestamp](https://github.com/jasonish/evebox/issues/31)

If i want to archive all events, i get an exception in ES.
`RemoteTransportException[[Numinus][192.168.1.67:9300][indices:data/read/search[phase/query]]]; nested: EsRejectedExecutionException[rejected execution of org.elasticsearch
.transport.TransportService$4@72c534b5 on EsThreadPoolExecutor[search, queue capacity = 4000, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@1ebae248[Runnin
g, pool size = 10, active threads = 10, queued tasks = 4000, completed tasks = 13493621]]];
Caused by: EsRejectedExecutionException[rejected execution of org.elasticsearch.transport.TransportService$4@72c534b5 on EsThreadPoolExecutor[search, queue capacity = 4000
, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@1ebae248[Running, pool size = 10, active threads = 10, queued tasks = 4000, completed tasks = 13493621]]]`

thx for any help here.
Stefan

**Comment by StefanSa** [comment]
Jason,
As already suspected works a single archive after which the timestamp is recognized correct.
Problems still make a bulk archive action, there is still an exception in ES.

To the problem there is a discussion at ES
[MultiSearch floods ES console](https://github.com/elastic/elasticsearch/issues/17771)

**Comment by jasonish** [comment]
Does archiving 2 or 3 work?  EveBox will execute up to 16 concurrent queries during an archive (provided you are archiving 16 or more events).  I'm guessing your server is quite busy?

I'll probably keep up at 16, but see if I can detect this and re-queue.

**Comment by jasonish** [comment]
Please try again with a package dated at least Oct. 17 2016.  Archiving has been moved server side and it will retry a few times are Elastic Search error conditions such as EsRejectedExecutionException.

**Comment by StefanSa** [comment]
Hi jason,
Now work as expected.
Although with high CPU load (1 month archiving), but all events are archived.

![cpu_load_evebox](https://cloud.githubusercontent.com/assets/6105075/19468003/864ef558-9514-11e6-982b-2eea8430b9c3.png)


Thanks for your effort and time at EveBox.
Stefan

**Comment by jasonish** [comment]
Archiving one month of events would push up the load for quite a while.  Unfortunately with elasticsearch you cannot update a document in-place.  As archiving adds a tag to the document, each archived document needs to be reindexed.
