### ISSUE TITLE
Alert commenting functionality

### ISSUE THREAD

**Issue by dfirdude** [jasonish/evebox#36]
We very much like the direction evebox is taking, thanks Jason!
One feature we're missing is a possibility to leave small comments/notes to alerts (or groups thereof). I'm thinking of something like the tags you're already using, but with user definable content. Something like:

```
    "comments": [
      "Tue, 15 Nov 2016 11:41:27 GMT: Comment 1",
      "Tue, 15 Nov 2016 11:42:36 GMT: Comment 2"
    ]
```

They don't need to be editable after saving them, another comment to the same alert would just be appended to the array.
Do you think this is feasible?

**Comment by jasonish** [comment]
Yes! This will be coming. The main holdup is I'm trying to move the data access layer to the backend to abstract the underlying data source to make elastic search an option.  But I see the commenting being added relatively soon as it doesn't require a full transition.

**Comment by jasonish** [comment]
Git master now allows commenting on alerts.
