### ISSUE TITLE
pfSense Suricata logs to Eve

### ISSUE THREAD

**Issue by garciarx** [jasonish/evebox#37]
I might have a unique use case but here it is.

I have a pfSense router that runs suricata, I'm moving the eve.json logs to logstash using filebeats.
How can I get the Flow, Payload and Packet data to show on the Eve website with the [PCAP] link to pull pcap.

**Comment by jasonish** [comment]
You are going to have to take a look at the eve-log configuration section in your suricata.yaml.  For packet and payload info you'll want to ensure that "packet" and/or "payload" option is enabled under "alerts".  As well you'll want to make sure that "flow" is enabled under the "eve-log" "types" section.

**Comment by garciarx** [comment]
Thanks, ill give it a try

**Comment by jasonish** [comment]
Closing. Re-open if needed.
