### ISSUE TITLE
No mapping found for [flow.age] in order to sort on

### ISSUE THREAD

**Issue by infiniteproject** [jasonish/evebox#39]
Im getting a lot of ES errors like this while loading reports/flow page:

`RemoteTransportException[[Kid Colt][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"aggs":{"topFlowsByAge":{"top_hits":{"size":10,"sort":[{"flow.age":{"order":"desc"}}]}}},"query":{"bool":{"filter":[{"exists":{"field":"event_type"}},{"term":{"event_type":"flow"}},{"range":{"@timestamp":{"gte":"2016-12-27T15:22:16+01:00"}}}]}},"size":0,"sort":[{"@timestamp":{"order":"desc"}}]}]]; nested: SearchParseException[No mapping found for [flow.age] in order to sort on];`

**Comment by jasonish** [comment]
Does this actually cause a problem with Evebox though?

I think the only way around this would be to create our own mapping, but keeping compatibility with Logstash/Kibana is higher priority right now.

**Comment by jasonish** [comment]
Fixed with 17a77765a4132687cd8cfc889ea89af2106dc33f
