### ISSUE TITLE
colorization of JSON output

### ISSUE THREAD

**Issue by inliniac** [jasonish/evebox#4]
Like Kibana3 can do. It has 'raw' and 'json', where the former has some nice colors for easier reading.

**Comment by jasonish** [comment]
I had played with this before so had some code sitting around.  I've not added a raw view (yet), but the colourized code cut and pastes out just find so I'm not sure if its really necessary.

The colours on the other hand may not be the best choice...

**Comment by inliniac** [comment]
I agree that the raw view may not be needed then. Is the color stuff in master? I think I'm running that but not seeing colors :)

**Comment by jasonish** [comment]
Yes, its commit 10c6b721c0762ee4eface0b1c476d52f8de5c57a.

Should look something like:
![screenshot from 2015-01-13 10 33 41](https://cloud.githubusercontent.com/assets/644115/5724199/b4a69c22-9b0f-11e4-973d-b82b1d8f5169.png)

**Comment by inliniac** [comment]
Ah, didn't realize you had just pushed it :)

Works nicely, thanks!
