### ISSUE TITLE
Displaying gzipped HTTP Payload

### ISSUE THREAD

**Issue by mschilt** [jasonish/evebox#40]
It would be great to have gzipped HTTP Payload unzipped before displaying.

**Comment by jasonish** [comment]
Hopefully this is a feature coming to Suricata soon.  When it does, I'll add update EveBox to display it.

https://twitter.com/Regiteric/status/843556651718397952

**Comment by jasonish** [comment]
Suricata 4.0.0rc1 included feature 2095 (https://redmine.openinfosecfoundation.org/issues/2095) which logs the decoded gzipped response body to eve.  Here is a screenshot with lastest EveBox updated to display this data in a better format:
![5904969623666688](https://user-images.githubusercontent.com/644115/27746407-c34375ba-5d8c-11e7-9682-f10b0c3ca6c9.png)
The HTTP response body shows you the decoded data. But you still see the gzipped content in the payload.

**Comment by mschilt** [comment]
\o/ .. woot!
