### ISSUE TITLE
Feature: Auto-archive after specific age.

### ISSUE THREAD

**Issue by jasonish** [jasonish/evebox#42]
I think it might be useful to have an option to auto-archive events after a certain amount of time (unit of days). Off by default, but can be enabled in the configuration file.

**Comment by torokp** [comment]
Would it be possible to auto-delete alert based on the age of the entries? To keep elasticsearch size down. For a normal installations, I think, alerts older than 30 days not really relevant.

**Comment by jasonish** [comment]
> Would it be possible to auto-delete alert based on the age of the entries? To keep elasticsearch size down. For a normal installations, I think, alerts older than 30 days not really relevant.

For Elastic Search I've chosen not to provide this functionality as using Elastic Curator is the defacto standard way to accomplish this, and the more I learn about elastic search, the harder it is to make a one size fits all tool, especially if curator is out there.

I do support this for the other datastores though.

**Comment by jasonish** [comment]
Closing. I no longer think this is important.
