### ISSUE TITLE
Cannot Escalate Standard Events

### ISSUE THREAD

**Issue by austin-taylor** [jasonish/evebox#46]
When I click "Escalate" on standard events, they do not show in Escalated. Only alerts show. Would like to be able to Escalate standard events as well.

**Comment by jasonish** [comment]
Its a bug that it gives you the option to escalate non-alert events - will fix. But I can see wanting non-alerts in the escalated view as well, but is harder than it looks as that uses the alert table, not the event table so doesn't do mixed types.  Will think about that one for a bit.

Would escalating non alerts really be that useful? On the longer term plan I was hoping to make "issues", or "tickets" or something which would be like an escalation, but contain a set of alerts and events chosen by the user that are all part of the related issue. Thoughts?

But back to just escalating non alerts, I'll probably do that. Unifying the different table views is on my mental to do list which would then make this a very trivial feature to add.

**Comment by austin-taylor** [comment]
Escalating non-alerts would be useful for items that alerts do not catch. I like the "Issues" or "tickets" escalation mentality because not all traffic is caught by alerts. 

Creating an issue and associating events/alerts would be ideal, but just the ability to highlight events of interest in the short term would be very helpful.

**Comment by jasonish** [comment]
Still worthwhile? Still using EveBox?

**Comment by jasonish** [comment]
Closing as out of scope for now.
