### ISSUE TITLE
Debian package upgrade failure

### ISSUE THREAD

**Issue by biolds** [jasonish/evebox#47]
I'm using packages on bintray on Debian, and upgrade is failing since recently:
```
# apt-get upgrade evebox
[...]
Preparing to unpack .../evebox_1%3a0.6.2~dev1492493921_amd64.deb ...
Unpacking evebox (1:0.6.2~dev1492493921) over (1:0.6.1~dev20170401053041) ...
Setting up evebox (1:0.6.2~dev1492493921) ...
Warning: The home dir /var/lib/evebox you specified already exists.
adduser: The user `evebox' already exists. Exiting.
dpkg: error processing package evebox (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 evebox
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
Thanks

**Comment by jasonish** [comment]
Will fix ASAP. But can you please tell me what version of Debian you are using? According to the Debian docs, the command I'm using to add the user is safe to call if the user exists, as in it doesn't exit with a failure, which is what I see on my test version.

Thanks.

**Comment by biolds** [comment]
It's running on a Debian Jessie in an lxc container (no systemd), hope that helps

**Comment by jasonish** [comment]
Should be fixed now. Also, if using the repos on Bintray, please consider updating your repos to the new location:

https://github.com/jasonish/evebox/wiki/EveBox-Debian-Repository

Bintray is still updated, at least for now.

**Comment by biolds** [comment]
Indeed it's fixed! Thanks for the fast answer.
