### ISSUE TITLE
view all in inbox not remembered across actions

### ISSUE THREAD

**Issue by inliniac** [jasonish/evebox#49]
By default inbox shows 100 events. At the top it says 'Showing 1-100 of 173.' I use the Drop down on the left to show all: 'view all'. Now I see 'Showing 1-173 of 173'.

When I archive an event, it jumps back to 'Showing 1-100 of 172.'.

Expected behavior: remember 'view all'.

Not sure how the user should be able to revert the option though. Perhaps replace the 'view all' by 'view 100' or something similar when viewing all.

**Comment by jasonish** [comment]
Did a quick fix that at least keeps it at view all after hitting the archive button. But overall the UI could use some improvement in this area.

**Comment by jasonish** [comment]
Close now. I've added a user configurable setting to set the number of alerts per page, You can set it up to 500.  Still ripe for improvement, but at least I think this issue is solved.

**Comment by inliniac** [comment]
Upgrade path isn't very clean yet. Inbox doesn't show anything unless you first to go settings and select an amount from the drop down. It should probably use a default if the value is missing.

**Comment by inliniac** [comment]
On 05-05-17 17:05, Jason Ish wrote:
> Thats because I didn't test on Firefox. Fix in build.

I use chromium btw, in case that matters.

**Comment by jasonish** [comment]
ah, maybe I had some local state, anyways, it was bad javascript that appeared to work in chrome, but not firefox... but given I normally use chrome, I may have had some local state causing it to not fail.
