### ISSUE TITLE
try to find relevant DNS data for transaction

### ISSUE THREAD

**Issue by inliniac** [jasonish/evebox#5]
If we have a http event, we generally know a host name, source and destination ip.

I think it could be very useful if evebox can show the most likely dns tx that resulted in the 'dest_ip'.

I guess in the common case you could search for src_ip, dest_ip as the answer in dns, the hostname as the A/AAAA/CNAME record... in a timeframe of a couple of seconds before the start of the flow.

**Comment by jasonish** [comment]
I've added rrname lookup for source and destination IP addresses in the extended event display.  If found, it will be displayed, otherwise it won't. 

I might try to make it more animated...  Where it says looking up, and then either displaying it or not found..
