### ISSUE TITLE
Debian stable repos is (no longer) correctly signed

### ISSUE THREAD

**Issue by johnefrancis** [jasonish/evebox#50]
When attempting an apt update, apt responds:

W: GPG error: http://evebox.org/files/debian stable InRelease: The following signatures were invalid: 0F23ABFF8F00056D52F1A82E4A72C4B48B15B19F
E: The repository 'http://files.evebox.org/evebox/debian stable InRelease' is not signed.

**Comment by jasonish** [comment]
Currently unable to replicate.  I just updated a Debian 8 test install that hadn't been updated for a few weeks without issue.  Fresh installs are fine.

If I *don't* install the key I get this:
```
W: GPG error: http://files.evebox.org stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4A72C4B48B15B19F
```
Suggesting that the repo is signed.

Did you migrate over from the bintray repo perhaps?

**Comment by johnefrancis** [comment]
Stumped. I definitely have the right key installed, I can see it with apt-key list

pub   rsa4096 2017-03-10 [SC]
      0F23 ABFF 8F00 056D 52F1  A82E 4A72 C4B4 8B15 B19F
uid           [ unknown] EveBox Automatic Package Signing Key <evebox@evebox.org>
sub   rsa4096 2017-03-10 [E]

I will see if I can manually check the sig. of the InRelease file.

I'm on Ubuntu 17.04.

**Comment by jasonish** [comment]
Ok, on 17.04 I get the same error. I usually only test on Debian. Will have to see whats up here.

**Comment by johnefrancis** [comment]
manual gpg seems happy enough with the key and InRelease. Not sure if the warning is the problem. 

john@u24b6-nzxt:~$ gpg --import ./GPG-KEY-evebox.txt 
gpg: key 4A72C4B48B15B19F: public key "EveBox Automatic Package Signing Key <evebox@evebox.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
john@u24b6-nzxt:~$ gpg --verify InRelease.txt 
gpg: Signature made Sun 23 Apr 2017 01:09:44 AM EDT
gpg:                using RSA key 4A72C4B48B15B19F
gpg: Good signature from "EveBox Automatic Package Signing Key <evebox@evebox.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 0F23 ABFF 8F00 056D 52F1  A82E 4A72 C4B4 8B15 B19F

**Comment by jasonish** [comment]
Probably related to this warning I get with Ubuntu 16.04:
```
W: http://files.evebox.org/evebox/debian/dists/stable/InRelease: Signature by key 0F23ABFF8F00056D52F1A82E4A72C4B48B15B19F uses weak digest algorithm (SHA1)
```
Maybe 17.04 got more strict.

Really don't want to cut a new key as it would break all existing setups.

**Comment by jasonish** [comment]
Please try again. Looks like I was able to fix this by changing my gpg configuration file and re-signing.

**Comment by johnefrancis** [comment]
Works now, thanks! Closing.
