### ISSUE TITLE
Getting HTTP/1.1 404 Not Found while archiving event

### ISSUE THREAD

**Issue by samirchauhan** [jasonish/evebox#53]
I sent a request to archive an event to the url: /api/1/event/AVyWHzgsJ-3JxxYdx60x/archive and in return I am getting 404 not found. I am trying to implement Evebox web app on my application by calling api's. Stuck into archiving and escalating events.

This issue is not specifically with Evebox web app. More like a query. Thank you for the awesome work on Evebox.

**Comment by samirchauhan** [comment]
This is curl request debug info:

erbose information:
<pre>* About to connect() to localhost port 5636 (#2)
*   Trying ::1...
* Connected to localhost (::1) port 5636 (#2)
&gt; GET /api/1/event/AVyWHzgsJ-3JxxYdx60x/archive HTTP/1.1
Host: localhost:5636
Accept: */*

&lt; HTTP/1.1 404 Not Found
&lt; Content-Type: text/plain; charset=utf-8
&lt; X-Content-Type-Options: nosniff
&lt; X-Evebox-Git-Revision: 8ef8639
&lt; X-Evebox-Session-Id: iIHXhS38zaETvpfpOiYgmlOynZdAUyz+/ryxXTXAFfNrDFCWP6Q4r+LWGqGDsSnD+ZsYqN03sgSrGowWCjIJ5A
&lt; Date: Fri, 30 Jun 2017 07:47:35 GMT
&lt; Content-Length: 19
&lt; 
* Connection #2 to host localhost left intact
</pre>

**Comment by jasonish** [comment]
Try a POST:
```
curl -XPOST -v http://localhost:5636/api/1/event/AVyWHzgsJ-3JxxYdx60x/archive
```

**Comment by jasonish** [comment]
Closing. EveBox follows the idea that GET should not cause side affects. So archive will never work with GET, must use POST.
