### ISSUE TITLE
Event Triggering, Alerts, and Notifications

### ISSUE THREAD

**Issue by brandonmreeves** [jasonish/evebox#59]
Would be great if evebox had something like this:

https://github.com/etsy/411

Allows for custom searches to create notifications, emails etc.

I have tried the above and it seems to work well. Would just be nice if it was integrated in evebox

**Comment by jasonish** [comment]
Saving search parameters is something I've thought about before. Had not thought too much about notifications tho. Marking as a feature for now.

**Comment by Fmstrat** [comment]
@jasonish I wouldn't reinvent the wheel. Users of a package like this are going to have very different needs. Instead, I would do what Home Assistant does (and many other apps), and create a notification plugin system.

This could be as simple as rolling the elements of any alert into a JSON, then creating a:

```
notification: /path/to/users/script.sh
```

Option in the evebox.yaml file. Whenever an alert comes in no matter what it is, that script is run with the JSON as parameter 1. The user can now do whatever they want. Maybe it's filter on regex (https://github.com/jasonish/evebox/issues/45) and then send an email, or make a curl call to Pushover to notify all their devices. It's up to that Administrator.

**Comment by jasonish** [comment]
Closing as I don't see myself getting to this anytime soon.
