### ISSUE TITLE
by source view for alerts

### ISSUE THREAD

**Issue by inliniac** [jasonish/evebox#6]
I would be interested in having a 'by source' tab in alerts. Then somehow in a compressed way show the alerts that apply to the source.

Color should indicate alert with highest severity. Highest severity event should be listed first.

I often see multiple events for a single host. E.g. ssh scan detected, weird ssh banner, host with bad rep, etc.

**Comment by jasonish** [comment]
I think I see what you are getting at...  Do an ES aggregation by source IP is not a problem, but its probably not going to work to pull all events for each source and display them in a compressed matter.  I could get the last 10, or perhaps last 100...  Or the last X high priority events or something like that...

The way I currently kind of do this is to open an event, click on an IP address in the "Event" panel and select "Search In Alerts".  Then I see the alerts in reverse chronological order for that IP.  But that requires more steps, and the view is only relevant for a single IP address.

**Comment by jasonish** [comment]
I'm not 100% sure what this would look like. Is this still something you'd like?

**Comment by jasonish** [comment]
Closing out old issues.  I'm still not sure what this would look like.
