### ISSUE TITLE
Release builds do not include webapp resources

### ISSUE THREAD

**Issue by rudolphfroger** [jasonish/evebox#63]
The release builds found at https://evebox.org/files/release/latest/ do not include the webapp resources (Javascript, CSS etc). I only checked the darwin and linux releases.

**Comment by jasonish** [comment]
I'm not sure what you mean. At least for the Linux release file there, I can download it, run it and then do a
```
curl http://localhost:5636/public/main.eadcc69251ea48bca49d.bundle.js
```
and get the javascript just fine, that is service from the webapp resources.

The other bundles are there as well.

Unfortunately I cannot test Darwin as I don't have a Mac anymore.

**Comment by rudolphfroger** [comment]
When I extract the tarball for Linux or Darwin, it only includes two files: the evebox binary and evebox.yaml.example. When using a HTTP proxy it would be nice to directly serve the Javascript, CSS and other webapp files and thus have theme included in the release tarballs.

**Comment by rudolphfroger** [comment]
Ok
