### ISSUE TITLE
Custom Field Names

### ISSUE THREAD

**Issue by SMAPPER** [jasonish/evebox#64]
Is there a way to integrate evebox with an existing Elasticsearch Stack that has Suricata data but has the field names renamed? For example, src_ip is source_ip to be consistent with other log sources.

**Comment by jasonish** [comment]
Not at this time. Sounds like a big job doing on the fly mapping, and then unmapping. Probably not something I'd be getting around to for sometime.

**Comment by bruberg** [comment]
I would like this feature as well. My mapping uses dst_ip and not dest_ip, for the same reason as mentioned above.

**Comment by jasonish** [comment]
Closing as there are no plans to do this.  An internal hard coded mapping will be done for ECS, but that is all I plan to do for on-the-fly mapping.
