### ISSUE TITLE
issue with broken eve.json logs

### ISSUE THREAD

**Issue by razuz** [jasonish/evebox#69]
Hey,

Time to time I'm seeing an issue raising with broken eve.json logs where packet data gets broken and therefore evefileprocessor.go is not entirely capable of parsing the json line. Effect is basically that file processor keep retry-ing until partition gets full. 

Would it be a viable option to just log the broken line and do not retry that ? maybe even as a config flag weather to retry or not ?

sample log : 
```
Feb 1 17:41:11 _host_ evebox[37242]: 2018-02-01 17:41:11 (bookmarker.go:71) -- Using bookmark file /var/log/suricata/eve.json.bookmark
Feb 1 17:41:11 _host_ evebox[37242]: 2018-02-01 17:41:11 (bookmarker.go:159) -- Found valid bookmark, jumping to offset 0
Feb 1 17:41:11 _host_ evebox[37242]: 2018-02-01 17:41:11 (evefileprocessor.go:112) -- Processing error, will retry: Failed to parse event: invalid character 't' after object key:value pair: {"timestamp":"2018-02-01T06:27:28.562297+0200","flow_id":311890176676985,"in_iface":"enp2s0f0","event_type":"alert","vlan":[253,253],"src_ip":"X.X.X.X","src_port":41948,"dest_ip":"Y.Y.Y.Y","dest_port":135,"proto":"TCP","alert":{"action":"allowed","gid":1,"signature_id":2001581,"rev":15,"signature":"ET SCAN Behavioral Unusual Port 135 traffic Potential Scan or Infection","category":"Misc activity","severity":3},"payload":"","payload_printable":"","stream":0,"packet":"_BROKEN_PACKET_DATA_{"timestamp":"2018-02-01T17:03:30.968175+0200","flow_id":1607763767772655,"in_iface":"enp2s0f0","event_type":"alert","vlan":[253,253],"src_ip":"X.X.X.X","src_port":38990,"dest_ip":"Y.Y.Y.Y","dest_port":135,"proto":"TCP","alert":{"action":"allowed","gid":1,"signature_id":2001581,"rev":15,"signature":"ET SCAN Behavioral Unusual Port 135 traffic Potential Scan or Infection","category":"Misc activity","severity":3},"payload":"","payload_printable":"","stream":0,"packet":"_packet_data_","packet_info":{"linktype":1}}
```

**Comment by jasonish** [comment]
Confirmed. This don't need to be a flag. This error was being caught as a file level error (doesn't exist), but in this case we should log it and move onto the next line. I have a fix ready. Will update this bug when its in a build (about an hour).

**Comment by jasonish** [comment]
@razuz Please try the latest git master build (https://evebox.org/files/development/)

I don't quite understand how your partition gets full though. EveBox doesn't delete any files. It does detect rotation by other tools though.

**Comment by razuz** [comment]
great stuff 🎉  ... looks good, but I'll confirm during the weekend

**Comment by jasonish** [comment]
Closing. I think I've sufficiently tested this one myself. If you can, please explain about your partition filling up though.
