### ISSUE TITLE
colorization of payload display

### ISSUE THREAD

**Issue by inliniac** [jasonish/evebox#7]
At least for HTTP, it would be nice if there could be some kind of colorization: highlight things generally interesting such as URL, User-Agent, etc.

**Comment by jasonish** [comment]
In master.

**Comment by jasonish** [comment]
Oops, got confused.  Thought this was colourization of JSON.

**Comment by jasonish** [comment]
Do you think this would be still be useful? Or would perhaps better organization of the "HTTP" panel that displays the "http" object be more valuable?

**Comment by jasonish** [comment]
I actually ask as I'm thinking of making the payload and packet panels a little more like a normal hex vs printable output.. Like Wireshark, or Sguil...

**Comment by jasonish** [comment]
Still want this?

**Comment by jasonish** [comment]
I don't see getting around to formatting the contents of the payload anytime soon.
