### ISSUE TITLE
Configure Evebox

### ISSUE THREAD

**Issue by berekese** [jasonish/evebox#71]
Hi, I have Suricata configured with eve log too. I installed evebox following steps:
```
sudo apt-get install wget
wget -qO - https://evebox.org/files/GPG-KEY-evebox | sudo apt-key add -
echo "deb http://files.evebox.org/evebox/debian stable main" | sudo tee /etc/apt/sources.list.d/evebox.list
sudo apt-get update
sudo apt-get install evebox
```

 I start daemon using: evebox -v -e http://localhost:9200, Here logs:

```
root@suricatanew:~# evebox -v -e http://localhost:9200
2018-02-05 13:10:02 (evebox.go:112) <Info> -- No command provided, defaulting to server.
2018-02-05 13:10:02 (server.go:176) <Info> -- This is EveBox Server version 0.8.1 (rev: 0633a54)
2018-02-05 13:10:02 (geoip-service.go:44) <Warning> -- Failed to initialize geoip database: no database files found
2018-02-05 13:10:02 (configdb.go:52) <Info> -- Using in-memory configuration DB.
2018-02-05 13:10:02 (migrator.go:68) <Debug> -- Initializing database.
2018-02-05 13:10:02 (migrator.go:79) <Info> -- Updating database to version 0.
2018-02-05 13:10:02 (migrator.go:79) <Info> -- Updating database to version 1.
2018-02-05 13:10:02 (server.go:295) <Info> -- Configuring ElasticSearch datastore
2018-02-05 13:10:02 (server.go:297) <Info> -- Using ElasticSearch URL http://localhost:9200
2018-02-05 13:10:02 (server.go:299) <Info> -- Using ElasticSearch Index logstash.
2018-02-05 13:10:02 (elasticsearch.go:107) <Info> -- Event base index: logstash
2018-02-05 13:10:02 (elasticsearch.go:108) <Info> -- Event search index: logstash-*
2018-02-05 13:10:02 (elasticsearch.go:155) <Debug> -- Fetching template _template/logstash
2018-02-05 13:10:02 (elasticsearch.go:117) <Debug> -- Decoding response (truncated at 1024 bytes): {}
2018-02-05 13:10:02 (elasticsearch.go:190) <Debug> -- Found template version <nil>
2018-02-05 13:10:02 (elasticsearch.go:197) <Warning> -- Failed to parse template, keyword resolution delayed.
2018-02-05 13:10:02 (elasticsearch.go:198) <Warning> -- Template: {}

```

But in website: http://My_IP:5636 I can't check any log, always I receive:
No events found. 

But I have a lot of logs on eve.log, stats.log and fast.log. How could I configure EveBox?

And as last question, are there way to add GeoLocation to Ips?

Thanks!!! and good job.

**Comment by jasonish** [comment]
How are you getting your events into Elastic Search?

**Comment by berekese** [comment]
I am newbie on this so maybe I am  not doing correctly all steps. I have installed elasticsearch 1.6 from .deb
`dpkg -i elasticsearch-1.6.1.deb`

After I start elasticsearch from daemon. After I start evobox from command line. 

I didn't change any conf, all default.

Here my netstat
```
# netstat -tlnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      141/rpcbind     
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1339/apache2    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      277/sshd        
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      2632/master     
tcp6       0      0 :::111                  :::*                    LISTEN      141/rpcbind     
tcp6       0      0 :::9200                 :::*                    LISTEN      4104/java       
tcp6       0      0 :::9300                 :::*                    LISTEN      4104/java       
tcp6       0      0 :::22                   :::*                    LISTEN      277/sshd        
tcp6       0      0 :::25                   :::*                    LISTEN      2632/master     
tcp6       0      0 :::5636                 :::*                    LISTEN      4187/evebox
```

**Comment by jasonish** [comment]
Ok, first you'll have to make sure you are running at least Elastic Search 5.  Any version 5 or 6 should work.

Usually people already have events in Elastic Search with Logstash. But if you don't have that setup you could try:
```
evebox -e http://localhost:9200 --input /var/log/suricata/eve.json
```

This will have evebox put the events into Elastic Search. Currently works well with ES5. I'm actively looking at issues with ES6, so your mileage may vary with Elastic Search 6.

**Comment by berekese** [comment]
Thanks you for your fast reply. I have to solve first how add variables to openvz Kernel or try with a KVM server. 

root@suricatanew:~# dpkg -i elasticsearch-6.1.3.deb 
Selecting previously unselected package elasticsearch.
(Reading database ... 40456 files and directories currently installed.)
Preparing to unpack elasticsearch-6.1.3.deb ...
Creating elasticsearch group... OK
Creating elasticsearch user... OK
Unpacking elasticsearch (6.1.3) ...
Setting up elasticsearch (6.1.3) ...
Job for systemd-sysctl.service failed because the control process exited with error code. See "systemctl status systemd-sysctl.service" and "journalctl -xe" for details.
Processing triggers for systemd (229-4ubuntu21) ...
root@suricatanew:~# journalctl -xe

F```
eb 05 13:45:58 suricatanew systemd[1]: Stopped Elasticsearch.
45:58 suricatanew systemd[1]: Stopped Elasticsearch.
-- Subject: Unit elasticsearch.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit elasticsearch.service has finished shutting down.
Feb 05 13:45:58 suricatanew systemd[1]: Reloading.
Feb 05 13:45:58 suricatanew systemd[1]: [/lib/systemd/system/vzfifo.service:19] Support for option SysVStartPriority= has been removed and it is ignored
Feb 05 13:45:58 suricatanew systemd[1]: Reloading.
Feb 05 13:45:58 suricatanew systemd[1]: [/lib/systemd/system/vzfifo.service:19] Support for option SysVStartPriority= has been removed and it is ignored
Feb 05 13:45:58 suricatanew systemd[1]: Reloading.
Feb 05 13:45:58 suricatanew systemd[1]: [/lib/systemd/system/vzfifo.service:19] Support for option SysVStartPriority= has been removed and it is ignored
Feb 05 13:46:10 suricatanew userdel[4358]: delete user 'elasticsearch'
Feb 05 13:46:10 suricatanew userdel[4358]: removed group 'elasticsearch' owned by 'elasticsearch'
Feb 05 13:46:10 suricatanew userdel[4358]: removed shadow group 'elasticsearch' owned by 'elasticsearch'
Feb 05 13:47:27 suricatanew groupadd[4386]: group added to /etc/group: name=elasticsearch, GID=118
Feb 05 13:47:27 suricatanew groupadd[4386]: group added to /etc/gshadow: name=elasticsearch
Feb 05 13:47:27 suricatanew groupadd[4386]: new group: name=elasticsearch, GID=118
Feb 05 13:47:27 suricatanew useradd[4392]: new user: name=elasticsearch, UID=111, GID=118, home=/home/elasticsearch, shell=/bin/false
Feb 05 13:47:27 suricatanew usermod[4397]: change user 'elasticsearch' password
Feb 05 13:47:27 suricatanew chage[4402]: changed password expiry for elasticsearch
Feb 05 13:47:27 suricatanew systemd[1]: Stopped Apply Kernel Variables.
-- Subject: Unit systemd-sysctl.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit systemd-sysctl.service has finished shutting down.
Feb 05 13:47:27 suricatanew systemd[1]: Starting Apply Kernel Variables...
-- Subject: Unit systemd-sysctl.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit systemd-sysctl.service has begun starting up.
Feb 05 13:47:27 suricatanew systemd-sysctl[4412]: Couldn't write '1' to 'fs/protected_symlinks', ignoring: No such file or directory
Feb 05 13:47:27 suricatanew systemd-sysctl[4412]: Couldn't write '262144' to 'vm/max_map_count', ignoring: Permission denied
Feb 05 13:47:27 suricatanew systemd-sysctl[4412]: Couldn't write '1' to 'kernel/kptr_restrict', ignoring: Permission denied
Feb 05 13:47:27 suricatanew systemd-sysctl[4412]: Couldn't write '1' to 'fs/protected_hardlinks', ignoring: No such file or directory
Feb 05 13:47:27 suricatanew systemd-sysctl[4412]: Couldn't write '176' to 'kernel/sysrq', ignoring: Permission denied
Feb 05 13:47:27 suricatanew systemd-sysctl[4412]: Couldn't write '1' to 'kernel/yama/ptrace_scope', ignoring: No such file or directory
Feb 05 13:47:27 suricatanew systemd[1]: systemd-sysctl.service: Main process exited, code=exited, status=1/FAILURE
Feb 05 13:47:27 suricatanew systemd[1]: Failed to start Apply Kernel Variables.
-- Subject: Unit systemd-sysctl.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit systemd-sysctl.service has failed.
-- 
-- The result is failed.
Feb 05 13:47:27 suricatanew systemd[1]: systemd-sysctl.service: Unit entered failed state.
Feb 05 13:47:27 suricatanew systemd[1]: systemd-sysctl.service: Failed with result 'exit-code'.
Feb 05 13:47:28 suricatanew systemd[1]: Reloading.
Feb 05 13:47:28 suricatanew systemd[1]: [/lib/systemd/system/vzfifo.service:19] Support for option SysVStartPriority= has been removed and it is ignored

```

**Comment by jasonish** [comment]
For starters it might be simpler to use the "TAR" download from https://www.elastic.co/downloads/elasticsearch. You can then start it like "./bin/elasticsearch -E discovery.type=single-node". I know that the systemd setup tries to up some default kernel parameters, which I don't think you can do under OpenVZ.

**Comment by berekese** [comment]
I think so, I will try to do it with another server. Thanks for all!

**Comment by berekese** [comment]
Hi Jasonish, I already have a server with all done but I can't see events.

Log evebox:
```
2018-02-06 10:55:22 (elasticsearch.go:308) <Warning> -- Search keyword not known, trying again.
2018-02-06 10:55:22 (elasticsearch.go:155) <Debug> -- Fetching template _template/logstash
2018-02-06 10:55:22 (elasticsearch.go:117) <Debug> -- Decoding response (truncated at 1024 bytes): {}
2018-02-06 10:55:22 (elasticsearch.go:190) <Debug> -- Found template version <nil>
2018-02-06 10:55:22 (elasticsearch.go:197) <Warning> -- Failed to parse template, keyword resolution delayed.
2018-02-06 10:55:22 (elasticsearch.go:198) <Warning> -- Template: {}
2018-02-06 10:55:22 (elasticsearch.go:236) <Info> -- Elastic Search keyword initialized to ""
2018-02-06 10:55:22 (datastore-alertquery.go:155) <Info> -- Query elapsed time: 6.987184ms
2018-02-06 10:55:28 (elasticsearch.go:308) <Warning> -- Search keyword not known, trying again.
2018-02-06 10:55:28 (elasticsearch.go:155) <Debug> -- Fetching template _template/logstash
2018-02-06 10:55:28 (elasticsearch.go:117) <Debug> -- Decoding response (truncated at 1024 bytes): {}
2018-02-06 10:55:28 (elasticsearch.go:190) <Debug> -- Found template version <nil>
2018-02-06 10:55:28 (elasticsearch.go:197) <Warning> -- Failed to parse template, keyword resolution delayed.
2018-02-06 10:55:28 (elasticsearch.go:198) <Warning> -- Template: {}
2018-02-06 10:55:28 (elasticsearch.go:236) <Info> -- Elastic Search keyword initialized to ""
2018-02-06 10:55:28 (datastore-alertquery.go:155) <Info> -- Query elapsed time: 36.153845ms
```

```
# netstat -tlnp
Conexiones activas de Internet (solo servidores)
Proto  Recib Enviad Dirección local         Dirección remota       Estado       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               ESCUCHAR    16522/sshd      
tcp6       0      0 127.0.0.1:9200          :::*                    ESCUCHAR    30497/java      
tcp6       0      0 ::1:9200                :::*                    ESCUCHAR    30497/java      
tcp6       0      0 127.0.0.1:9300          :::*                    ESCUCHAR    30497/java      
tcp6       0      0 ::1:9300                :::*                    ESCUCHAR    30497/java      
tcp6       0      0 :::22                   :::*                    ESCUCHAR    16522/sshd      
tcp6       0      0 :::5636                 :::*                    ESCUCHAR    30735/evebox
```

```
# /etc/init.d/elasticsearch status
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; disabled; vendor preset: enabled)
   Active: active (running) since mar 2018-02-06 10:49:54 CET; 6min ago
     Docs: http://www.elastic.co
 Main PID: 30497 (java)
    Tasks: 31
   Memory: 1.2G
      CPU: 10.818s
   CGroup: /system.slice/elasticsearch.service
           └─30497 /usr/bin/java -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+AlwaysPreTouch -server -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.no...
feb 06 10:49:54 suricata systemd[1]: Started Elasticsearch.
```
And I have logs on eve.log, fast.log and stats.log.

How could I get logs in website? and How could I add geoip? Are there any map or anything so?

Thanks!!!

**Comment by jasonish** [comment]
So you've caught me in the middle of fixing up the Elastic Search 6 support, so I think I've got it now. If you update to the latest development build (https://evebox.org/files/development/) we should be able to get things working.

First, verify that you actually have eve alerts:
```
cat /var/log/suricata/eve.json
```
Do you see stuff?

Now start evebox:
```
evebox server -e http://localhost:9200 --input /var/log/suricata/eve.json --input-start -v
````
This will complain a bit while it can't find the index, but it will eventually create the index and be OK.

You might also try "demo/oneshot" mode. This does not use Elastic Search, but an embedded database instead:
```
evebox oneshot /var/log/suricata/eve.json
```
But its only really useful for testing.

Once we get this working, we'll move onto geoip.

**Comment by berekese** [comment]
Thanks for reply.

I downloaded latest version, I started evebox and its log:

```
# evebox server -e http://localhost:9200 --input /var/log/suricata/eve.json --input-start -v
2018-02-07 11:38:28 (server.go:176) <Info> -- This is EveBox Server version 0.9.0dev (rev: c97eb9f); os=linux, arch=amd64
2018-02-07 11:38:28 (geoip-service.go:44) <Warning> -- Failed to initialize geoip database: no database files found
2018-02-07 11:38:28 (configdb.go:52) <Info> -- Using in-memory configuration DB.
2018-02-07 11:38:28 (migrator.go:68) <Debug> -- Initializing database.
2018-02-07 11:38:28 (migrator.go:79) <Info> -- Updating database to version 0.
2018-02-07 11:38:28 (migrator.go:79) <Info> -- Updating database to version 1.
2018-02-07 11:38:28 (server.go:294) <Info> -- Configuring ElasticSearch datastore
2018-02-07 11:38:28 (server.go:295) <Info> -- Using ElasticSearch URL http://localhost:9200
2018-02-07 11:38:28 (server.go:297) <Info> -- Using ElasticSearch Index logstash.
2018-02-07 11:38:28 (elasticsearch.go:111) <Info> -- Event base index: logstash
2018-02-07 11:38:28 (elasticsearch.go:112) <Info> -- Event search index: logstash-*
2018-02-07 11:38:28 (server.go:317) <Info> -- Connected to Elastic Search (version: 6.1.3)
2018-02-07 11:38:28 (elasticsearch.go:159) <Debug> -- Fetching template _template/logstash
2018-02-07 11:38:28 (elasticsearch.go:120) <Debug> -- Decoding response (truncated at 1024 bytes): {"logstash":{"order":0,"version":60001,"index_patterns":["logstash-*"],"settings":{"index":{"refresh_interval":"5s"}},"mappings":{"_default_":{"dynamic_templates":[{"message_field":{"path_match":"message","match_mapping_type":"string","mapping":{"type":"text","norms":false}}},{"string_fields":{"match":"*","match_mapping_type":"string","mapping":{"type":"text","norms":false,"fields":{"keyword":{"type":"keyword","ignore_above":256}}}}}],"properties":{"@timestamp":{"type":"date"},"@version":{"type":"keyword"},"geoip":{"dynamic":true,"properties":{"ip":{"type":"ip"},"location":{"type":"geo_point"},"latitude":{"type":"half_float"},"longitude":{"type":"half_float"}}}}}},"aliases":{}}}
2018-02-07 11:38:28 (elasticsearch.go:198) <Debug> -- Found template version 60001
2018-02-07 11:38:28 (elasticsearch.go:256) <Info> -- Elastic Search keyword initialized to "keyword"
2018-02-07 11:38:28 (server.go:431) <Info> -- Configuring internal eve log reader
2018-02-07 11:38:28 (server.go:131) <Info> -- Session reaper started
2018-02-07 11:38:28 (server.go:165) <Info> -- Authentication disabled.
2018-02-07 11:38:28 (server.go:276) <Info> -- Listening on 0.0.0.0:5636
2018-02-07 11:38:28 (bookmarker.go:71) <Info> -- Using bookmark file /var/log/suricata/eve.json.bookmark
2018-02-07 11:38:28 (bookmarker.go:159) <Info> -- Found valid bookmark, jumping to offset 1144763
```
Website loads correctly. I have logs on stats and eve.json but not in fast.log.
Should I have suricata started in another terminal with something so?

suricata -c /etc/suricata/suricata.yaml -i ens3

In website I haven't any info. What more should I do?

Thanks!

**Comment by jasonish** [comment]
So EveBox won't do anything with Suricata. You have to start and stop it yourself. EveBox is only a log reporting tool. You'll also need to make sure you have rules loaded.

EveBox only uses eve.json, so you don't need fast.log or stats.log for it. 

To get GeoIP working, you can do something like:
```
mkdir /etc/evebox
cd /etc/evebox
curl -OL http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz
```
then re-start EveBox.

Unfortunately EveBox doesn't have a map that it will plot events on it. Kibana does. Have you looked into SELKS (https://github.com/StamusNetworks/SELKS), it bundles Suricata, EveBox, Elastic Search and Kibana into one VM.

**Comment by jasonish** [comment]
Alternatively, is using Docker an option for you?

**Comment by berekese** [comment]
Thanks you @jasonish , the problem is that in .eve.json I have a lot of flows, its okay but I haven't any "attacker" on my net, and its rare because when I installed a Suricata only I had a lot of lines on fast.log alerting from attacks, maybe are rules? 
In suricata.yaml I have: default-rule-path: /etc/suricata/rules

To clarity all, I should to install for my side; suricata, elastic and after, use EvoBox, right?

I am obsessing with that my problem is that. I have a lot of flows but not alerts on fast.log and its rare because I yesterday had rules on that file
```
 02/06/2018-10:28:39.895169  [**] [1:2402000:4709] ET DROP Dshield Block Listed Source group 1 [**] [Classification: Misc Attack] [Priority: 2] {TCP} 66.111.57.55:59073 -> 192.168.XX.XX:5934
02/06/2018-10:28:41.552029  [**] [1:2402000:4709] ET DROP Dshield Block Listed Source group 1 [**] [Classification: Misc Attack] [Priority: 2] {TCP} 185.107.83.53:49987 -> 192.168.XX.XX:8080
02/06/2018-10:28:44.097827  [**] [1:2013031:5] ET POLICY Python-urllib/ Suspicious User Agent [**] [Classification: Attempted Information Leak] [Priority: 2] {TCP} 192.168.XX.XX:43102 -> 91.189.95.15:80
02/06/2018-10:29:52.861213  [**] [1:2403316:38196] ET CINS Active Threat Intelligence Poor Reputation IP group 17 [**] [Classification: Misc Attack] [Priority: 2] {TCP} 38.104.1.186:51048 -> 192.168.1.101:443
02/06/2018-10:30:34.407314  [**] [1:2402000:4709] ET DROP Dshield Block Listed Source group 1 [**] [Classification: Misc Attack] [Priority: 2] {TCP} 5.188.86.12:48456 -> 192.168.XX.XX:23389
02/06/2018-10:30:34.407314  [**] [1:2403303:38196] ET CINS Active Threat Intelligence Poor Reputation IP group 4 [**] [Classification: Misc Attack] [Priority: 2] {TCP} 5.188.86.12:48456 -> 192.168.XX.XX:23389
02/06/2018-10:36:31.599344  [**] [1:2402000:4709] ET DROP Dshield Block Listed Source group 1 [**] [Classification: Misc Attack] [Priority: 2] {TCP} 5.188.86.41:40868 -> 192.168.XX.XX:4326
02/06/2018-10:36:31.599344  [**] [1:2403303:38196] ET CINS Active Threat Intelligence Poor Reputation IP group 4 [**] [Classification: Misc Attack] [Priority: 2] {TCP} 5.188.86.41:40868 -> 192.168.XX.XX:4326
02/06/2018-10:36:59.776314  [**] [1:2010935:2] ET POLICY Suspicious inbound to MSSQL port 1433 [**] [Classification: Potentially Bad Traffic] [Priority: 2] {TCP} 14.124.118.80:40378 -> 192.168.XX.XX:1433
02/06/2018-10:38:43.542399  [**] [1:2403316:38196] ET CINS Active Threat Intelligence Poor Reputation IP group 17 [**] [Classification: Misc Attack] [Priority: 2] {TCP} 38.142.192.82:10978 -> 192.168.XX.XX:5000
02/06/2018-10:41:07.083292  [**] [1:2402000:4709] ET DROP Dshield Block Listed Source group 1 [**] [Classification: Misc Attack] [Priority: 2] {TCP} 77.72.82.80:58692 -> 192.168.XX.XX:7401
02/06/2018-10:41:07.083292  [**] [1:2403358:38196] ET CINS Active Threat Intelligence Poor Reputation IP group 59 [**] [Classification: Misc Attack] [Priority: 2] {TCP} 77.72.82.80:58692 -> 192.168.XX.XX:7401
02/06/2018-10:42:19.176209  [**] [1:2402000:4709] ET DROP Dshield Block Listed Source group 1 [**] [Classification: Misc Attack] [Priority: 2] {TCP} 77.72.82.92:58891 -> 192.168.XX.XX:11160
02/06/2018-10:42:19.176209  [**] [1:2403358:38196] ET CINS Active Threat Intelligence Poor Reputation IP group 59 [**] [Classification: Misc Attack] [Priority: 2] {TCP} 77.72.82.92:58891 -> 192.168.XX.XX:11160
02/06/2018-10:42:22.517439  [**] [1:2403336:38196] ET CINS Active Threat Intelligence Poor Reputation IP group 37 [**] [Classification: Misc Attack] [Priority: 2] {TCP} 59.168.199.152:63623 -> 192.168.XX.XX:23
02/06/2018-10:55:43.812773  [**] [1:2402000:4709] ET DROP Dshield Block Listed Source group 1 [**] [Classification: Misc Attack] [Priority: 2] {TCP} 80.82.77.139:44738 -> 192.168.XX.XX:6379
02/06/2018-10:55:43.812773  [**] [1:2403363:38196] ET CINS Active Threat Intelligence Poor Reputation IP group 64 [**] [Classification: Misc Attack] [Priority: 2] {TCP} 80.82.77.139:44738 -> 192.168.XX.XX:6379
```
When I had all that alerts I could see on EveBox a lot of traffic and its works wonderful.
I test SELKS, too a good tool but I have same problem, all on eve.json but I can't see actual alerts.  I should be forgotten something basic I think.

I have in another server ELK + Suricata, and it works but for default, template Kibana isn't so good for my bosses and the latest template for Suricata its for Kibana 3 or 4

BTW, I never used Docker, what do you think about that?

Thanks!!!

**Comment by jasonish** [comment]
Sounds like you are very close. To test that rules are firing I usually visit http://www.testmyids.com in a way that will be seen by Suricata. There is a rule in the ET/Open ruleset that you are using that will trigger on that.  I usually just do something like "curl http://www.testmyids.com" from a host where it will be seen by Suricata.

You might also want to check the HOME_NET setting in your suricata.yaml, to make sure it matches your network where Suricata is listening.

**Comment by berekese** [comment]
Yes, finally with that test I see traffic on fast.log
```
02/07/2018-14:30:55.178843  [**] [1:2013028:4] ET POLICY curl User-Agent Outbound [**] [Classification: Attempted Information Leak] [Priority: 2] {TCP} 192.168.XX.XX:33478 -> 82.165.177.154:80
02/07/2018-14:30:55.179990  [**] [1:2100498:7] GPL ATTACK_RESPONSE id check returned root [**] [Classification: Potentially Bad Traffic] [Priority: 2] {UDP} 192.168.XX.XX:46708 -> 192.168.XX.XX:37008
02/07/2018-14:30:55.180156  [**] [1:2100498:7] GPL ATTACK_RESPONSE id check returned root [**] [Classification: Potentially Bad Traffic] [Priority: 2] {UDP} 192.168.XX.XX:46708 -> 192.168.XX.XX:37008
02/07/2018-14:30:55.180157  [**] [1:2100498:7] GPL ATTACK_RESPONSE id check returned root [**] [Classification: Potentially Bad Traffic] [Priority: 2] {UDP} 192.168.XX.XX:46708 -> 192.168.XX.XX:37008
02/07/2018-14:30:55.221267  [**] [1:2100498:7] GPL ATTACK_RESPONSE id check returned root [**] [Classification: Potentially Bad Traffic] [Priority: 2] {TCP} 82.165.177.154:80 -> 192.168.XX.XX:33478
```
I can see alerts using SELKS
ttp://i68.tinypic.com/ofzrz4.png

Now I am waiting that my partners work and I can test more alerts.  SELKS hasn't any world map I think, right?
I will learn Kibana too or maybe downgrade Kibana 3 or 4 and use template suricata that I saw on a website. 

However, I want to thank you your time, your patience and your work. Its a bless to find people that wants help. Sorry for my english, Im spanish.

Thanks you one more time @jasonish

**Comment by jasonish** [comment]
I am pretty sure that older Kibana doesn't work on newer Elastic Search. You are forced to run the newer one. Probably worth learning anyways. I see that SELKS does have a world-map view in their "Alert" display in Kibana. So probably just a matter of learning how to do that in Kibana.

**Comment by berekese** [comment]
Ops, thanks I will try so :)

**Comment by jasonish** [comment]
Closing for now. With some elasticsearch issues fixed during the progression of this issue, I think it now just falls into support.

**Comment by mike97-dotcom** [comment]
hello I have a problem with evebox. I am a novice in the field, indeed I use suricata, elasticsearch, and logstash, and when I want to connect evebox to elasticsearch it shows me this error, but it is only evebox that is connected to port 5636
![evebox](https://user-images.githubusercontent.com/72115171/95264739-cc580780-0827-11eb-8667-b2141c8ef7bb.PNG)

**Comment by mike97-dotcom** [comment]
with netstat , we have 
![Uploading netstat.PNG…]()

**Comment by mike97-dotcom** [comment]
![Uploading netstat.PNG…]()

**Comment by mike97-dotcom** [comment]
@jasonish  please i need help

**Comment by jasonish** [comment]
It looks as though something else is bound to port 5636... Perhaps another evebox instance? As a quick work-around you could try the `-p` option to run it on another port.
