### ISSUE TITLE
Error when i try to build evebox

### ISSUE THREAD

**Issue by yeknu** [jasonish/evebox#75]
Hello, 

I'm trying to build evebox on a clean instalation of debian and getting the next error.

Node version= v8.11.1
npm version =  5.6.0
Golang version = go version go1.10.1 linux/amd64

/go/src/github.com/jasonish/evebox# make install-deps
make -C webapp install-deps
make[1]: Entering directory '/root/go/src/github.com/jasonish/evebox/webapp'
npm install

> node-sass@4.7.2 install /root/go/src/github.com/jasonish/evebox/webapp/node_modules/node-sass
> node scripts/install.js

module.js:549
    throw err;
    ^

Error: Cannot find module '/root/go/src/github.com/jasonish/evebox/webapp/node_modules/node-sass/scripts/install.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

> uglifyjs-webpack-plugin@0.4.6 postinstall /root/go/src/github.com/jasonish/evebox/webapp/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

module.js:549
    throw err;
    ^

Error: Cannot find module '/root/go/src/github.com/jasonish/evebox/webapp/node_modules/webpack/node_modules/uglifyjs-webpack-plugin/lib/post_install.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.7.2 (node_modules/node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.7.2 install: `node scripts/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-27T12_20_22_668Z-debug.log
Makefile:27: recipe for target 'install-deps' failed
make[1]: *** [install-deps] Error 1
make[1]: Leaving directory '/root/go/src/github.com/jasonish/evebox/webapp'
Makefile:44: recipe for target 'install-deps' failed
make: *** [install-deps] Error 2

I tried to install manually node-saas but it results imposible.

¿Some solution for this?

**Comment by jasonish** [comment]
How did you install node? With a fresh Debian 9 docker container I installed node v8.11.1 with nvm and it appears to work. You can isolate this a bit with:
```
cd webapp
npm install
```

**Comment by yeknu** [comment]
I have installed node with the binaries provided in the oficial website.

I'm gona try with nvm and give you feedback.

Thanks

**Comment by yeknu** [comment]
It seems to be working well, just getting 2 warnings.


Binary found at /root/go/src/github.com/jasonish/evebox/webapp/node_modules/node-sass/vendor/linux-x64-57/binding.node
Testing binary
Binary is fine
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})


Thanks for your help
