### ISSUE TITLE
Inbox / Alerts / Reports Empty

### ISSUE THREAD

**Issue by sitbk** [jasonish/evebox#76]
I initially reported this issue over at the SELKS Google Group at https://groups.google.com/forum/#!topic/selks/JQ5VpvaMoiw

Evebox's Inbox and Alerts appear entirely empty while the reports pages populate the graph at the top but lack any data in their tables. The Events page populates properly. The above link contains the template logstash is currently using. Running "systemctl status evebox -l" nets the following message:

May 28 09:19:37 SELKS evebox[3597]: 2018-05-28 09:19:37 (elasticsearch.go:319) <Warning> -- Search keyword not known, trying again.
May 28 09:19:37 SELKS evebox[3597]: 2018-05-28 09:19:37 (elasticsearch.go:202) <Info> -- Found templates [logstash]
May 28 09:19:37 SELKS evebox[3597]: 2018-05-28 09:19:37 (elasticsearch.go:244) <Warning> -- Failed to determine Elastic Search keyword suffix, EveBox may not work properly.

![dnsreport](https://user-images.githubusercontent.com/29120973/40592290-47b4c2a6-6258-11e8-94ff-15e0ddc6e265.png)
![events](https://user-images.githubusercontent.com/29120973/40592291-47e0a420-6258-11e8-8fbe-afd2f6d53037.png)
![alerts](https://user-images.githubusercontent.com/29120973/40592292-480bed88-6258-11e8-8d20-f02a68017ec5.png)
![inbox](https://user-images.githubusercontent.com/29120973/40592293-48365564-6258-11e8-9a1b-4101c03973b4.png)

**Comment by jasonish** [comment]
From the template you posted to the group it looks like this install may be quite old and have been upgraded from Elastic Search 2 to Elastic Search 5. Does that sound right?

Anyways, are you able to start EveBox in a terminal for me on a different port on your SELKS install?
```
evebox server --elasticsearch-keyword raw -p 9999
```

Then connect to it on port 9999 and see if the inbox works?

Thanks.

**Comment by jasonish** [comment]
It looks like there may have been issues with your SELKS upgrades. While you are clearly running Elastic Search 5+, you still are using an Elastic Search 2 template which is not being detected as I have dropped support for Elastic Search 2. Its a trivial fix here tho, to work with Elastic Search 5+ with a v2 template, so I'm going to fix it on this end. I plan to do a release today or tomorrow once another issue is fixed, which will include a fix for this, so you don't have to provide a custom config.

**Comment by jasonish** [comment]
Should be fixed in 0.9.1.

**Comment by sitbk** [comment]
Thanks for the quick turn-around, works like a charm.
