### ISSUE TITLE
Provide output to influxdb

### ISSUE THREAD

**Issue by aimdev** [jasonish/evebox#79]
Provide a means to send data to an influxdb (https://www.influxdata.com/time-series-platform/) database via telegraf.

Thanks

Aimdev

**Comment by aimdev** [comment]
Hi

As far as I can see you push data into a elastic search temporal database.

It may be a better option to avoid telegraf, which seems to just ’tail’ the file, 
with no bookmark capability,  and reproduce a push directly into influxDb temporal database.

There is an api, here

https://docs.influxdata.com/influxdb/v1.6/guides/writing_data/ <https://docs.influxdata.com/influxdb/v1.6/guides/writing_data/>

Currently doing the evebox - elastic search - grafana( https://grafana.com <https://grafana.com/>) is proving difficult (your bit seems to be working ok).
so I am looking for a possible alternative.

Thanks

AimDev

**Comment by jasonish** [comment]
I’m not sure I see the fit. Seems like an independent tool is best for this as it doesn’t benefit EveBox at all. Have you checked if you can get the same stuff you are looking for out of Kibana?

**Comment by aimdev** [comment]
Hi

I moved from ELK to TIKS + Grafana a while back as they were resource hungry, and 
Kibana is not as intuitive as Chrongraf  which is used as a precursor to Grafana.

Thanks

AimDev

**Comment by aimdev** [comment]
Hi

Just in addition, I felt it would be useful to provide output to another time based database, ie influxdb.
Using logstash is very difficult to get correct. and IMHO not very efficient.

Thanks

AimDev

**Comment by jasonish** [comment]
Closing for now as this is out of scope for the current goals of EveBox.
