### ISSUE TITLE
Pager not working

### ISSUE THREAD

**Issue by dfirdude** [jasonish/evebox#8]
We don't get the pager to work (next / prev buttons). E.g. says it's on events 101 to 200, but in fact still shows first page (i.e latest events).

**Comment by jasonish** [comment]
Which version are you using?  One of the tagged builds are git master?  Will fix this a.s.a.p.

**Comment by dfirdude** [comment]
We're using git master. Tried tagged too, experienced same result.

**Comment by jasonish** [comment]
Fix on the alert views, the "all" event view seemed to work properly already.

Thanks for the report.

**Comment by dfirbuddy** [comment]
I can confirm, that the other->all view is working, but not alerts->next.

**Comment by dfirdude** [comment]
Works for me now, thanks Jason!

**Comment by dfirbuddy** [comment]
Yes works for me too. Thanks
