### ISSUE TITLE
GeoIP Data using the paid GeoIP-City dataset?

### ISSUE THREAD

**Issue by csanate** [jasonish/evebox#80]
I attempted to use the paid version of the Maxmind GeoIP database, but Eve doesn't seem to recognize it. Also looking at https://github.com/jasonish/evebox/blob/master/geoip/geoip.go it seems there are some explicit references to the Lite version of the database. Would it be possible to get support for this?

Thanks!

**Comment by jasonish** [comment]
At some point during startup you should see an error message:
```
Unsupported database type: ...
```
Can you tell me what the type is?

Thanks.

**Comment by jasonish** [comment]
Closing due to lack of feedback.
