### ISSUE TITLE
ARM architecture support

### ISSUE THREAD

**Issue by sgabe** [jasonish/evebox#81]
EveBox seems to be a good choice for Raspberry Pi because it is a lightweight solution with little overhead. Are there any plans for ARM support?

**Comment by jasonish** [comment]
For this to happen I’ll need someone to show me how, or a contribute a working cross compilation of the Go binary to arm. The node stuff can be done on another machine. 

It’s not a trivial Go cross compile due to SQLite. 

I may get to it someday myself as Arm support is asked for now and then. And who knows, some may be building it already for arm.

**Comment by sgabe** [comment]
Note that both Go and Node.js works on ARM.

**Comment by jasonish** [comment]
I’m curious, have you tried building on arm? Without an arm I’m not tempted to do this myself. If I can cross compile I’ll happily release arm binaries.

**Comment by sgabe** [comment]
Currently the build process fails on ARM with the following errors:
```
root@pi:/opt/evebox # node -v
v8.11.1
root@pi:/opt/evebox # go version
go version go1.11.1 linux/arm
root@pi:/opt/evebox # make install-deps
make -C webapp install-deps
make[1]: Entering directory '/opt/evebox/webapp'
npm install
(node:18239) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:120:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.71-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /opt/evebox/webapp
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/evebox/webapp/npm-debug.log
npm ERR! not ok code 0
Makefile:27: recipe for target 'install-deps' failed
make[1]: *** [install-deps] Error 1
make[1]: Leaving directory '/opt/evebox/webapp'
Makefile:43: recipe for target 'install-deps' failed
make: *** [install-deps] Error 2
```
Let me know if you have any ideas, I can help with the testing.

**Comment by sgabe** [comment]
It seems I got an ancient version of NPM and needed `npm install -g npm@latest` to upgrade it.

**Comment by sgabe** [comment]
The build process completed after upgrading NPM to version 6.4.1. However, after I launch EveBox with `evebox server -v -D /var/lib/evebox --datastore sqlite --input /var/log/suricata/eve.json` I only get `404 page not found` when I visit http://localhost:5636.

```
root@pi:~/go/src/evebox # make install-deps
make -C webapp install-deps
make[1]: Entering directory '/root/go/src/evebox/webapp'
npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/@angular-devkit/core/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

audited 23892 packages in 76.466s
found 29 vulnerabilities (21 low, 8 high)
  run `npm audit fix` to fix them, or `npm audit` for details
make[1]: Leaving directory '/root/go/src/evebox/webapp'
go get github.com/golang/dep/cmd/dep
go get github.com/cespare/reflex
go get github.com/gobuffalo/packr/packr
/root/go/bin/dep ensure -v
root@pi:~/go/src/evebox # make
cd webapp && make
make[1]: Entering directory '/root/go/src/evebox/webapp'
Exporting GITREV = 3cfd74e.
Building EveBox webapp rev 3cfd74e.
./node_modules/.bin/ng build --aot --prod --output-path ../resources/public --deploy-url "public/"

Date: 2018-10-29T21:41:20.199Z
Hash: 6288f05125412c884814
Time: 646179ms
chunk {0} runtime.cd1930dfc8cce42a4850.js (runtime) 1.45 kB [entry] [rendered]
chunk {1} main.078852891ad1825e3649.js (main) 2.65 MB [initial] [rendered]
chunk {2} polyfills.db84b0d82268f31e7a80.js (polyfills) 59.4 kB [initial] [rendered]
chunk {3} styles.7457cf6e6bb6e4373c6c.css (styles) 0 bytes [initial] [rendered]
make[1]: Leaving directory '/root/go/src/evebox/webapp'
touch resources/public/_done
root@pi:~/go/src/evebox # ./evebox server -v -D /var/lib/evebox --datastore sqlite --input /var/log/suricata/eve.json
2018-10-29 22:50:51 (server.go:176) <Info> -- This is EveBox Server version  (rev: ); os=linux, arch=arm
2018-10-29 22:50:51 (geoip-service.go:44) <Warning> -- Failed to initialize geoip database: no database files found
2018-10-29 22:50:51 (configdb.go:59) <Info> -- Using configuration database file /var/lib/evebox/config.sqlite
2018-10-29 22:50:51 (migrator.go:66) <Debug> -- Current database schema version: 1
2018-10-29 22:50:51 (resources.go:50) <Warning> -- Failed to find box asset ./resources/configdb/V2.sql.
2018-10-29 22:50:51 (sqlite.go:140) <Info> -- Configuring SQLite datastore
2018-10-29 22:50:51 (sqlite.go:146) <Info> -- SQLite event store using file /var/lib/evebox/events.sqlite
2018-10-29 22:50:51 (sqlite.go:60) <Debug> -- Opening SQLite database /var/lib/evebox/events.sqlite
2018-10-29 22:50:51 (migrator.go:66) <Debug> -- Current database schema version: 2
2018-10-29 22:50:51 (resources.go:50) <Warning> -- Failed to find box asset ./resources/sqlite/V3.sql.
2018-10-29 22:50:51 (sqlite.go:94) <Info> -- Retention period: 0 days
2018-10-29 22:50:51 (server.go:446) <Info> -- Configuring internal eve log reader
2018-10-29 22:50:51 (server.go:131) <Info> -- Session reaper started
2018-10-29 22:50:51 (server.go:165) <Info> -- Authentication disabled.
2018-10-29 22:50:51 (server.go:276) <Info> -- Listening on 0.0.0.0:5636
2018-10-29 22:50:51 (bookmarker.go:71) <Info> -- Using bookmark file /var/log/suricata/eve.json.bookmark
2018-10-29 22:50:51 (bookmarker.go:159) <Info> -- Found valid bookmark, jumping to offset 10995
2018-10-29 22:51:18 (anonymous.go:64) <Info> -- Logging in anonymous user {anonymous} from 192.168.0.199:20858
2018-10-29 22:51:26 (anonymous.go:64) <Info> -- Logging in anonymous user {anonymous} from 192.168.0.199:20858
2018-10-29 22:51:51 (server.go:127) <Debug> -- Reaping sessions.
```

**Comment by jasonish** [comment]
So close. For some reason the web resources are not being embedded into the binary.

It does look like the web artifacts built correctly, but the evebox binary didn't rebuild after. Given the state above try:
```
rm -f evebox
make
```

**Comment by sgabe** [comment]
The result is the same 404 message:
```
root@pi:~/go/src/evebox # rm -f evebox
root@pi:~/go/src/evebox # make
/root/go/bin/packr -z
CGO_ENABLED=1 go build --tags "fts5 json1" \
        -ldflags "-X \"github.com/jasonish/evebox/core.BuildRev=3cfd74e\" -X \"github.com/jasonish/evebox/core.BuildVersion=0.9.1\" " \
        cmd/evebox.go
root@pi:~/go/src/evebox # ./evebox server -v -D /var/lib/evebox --datastore sqlite --input /var/log/suricata/eve.json
2018-10-29 23:39:00 (server.go:176) <Info> -- This is EveBox Server version  (rev: ); os=linux, arch=arm
2018-10-29 23:39:00 (geoip-service.go:44) <Warning> -- Failed to initialize geoip database: no database files found
2018-10-29 23:39:00 (configdb.go:59) <Info> -- Using configuration database file /var/lib/evebox/config.sqlite
2018-10-29 23:39:00 (migrator.go:66) <Debug> -- Current database schema version: 1
2018-10-29 23:39:00 (resources.go:50) <Warning> -- Failed to find box asset ./resources/configdb/V2.sql.
2018-10-29 23:39:00 (sqlite.go:140) <Info> -- Configuring SQLite datastore
2018-10-29 23:39:00 (sqlite.go:146) <Info> -- SQLite event store using file /var/lib/evebox/events.sqlite
2018-10-29 23:39:00 (sqlite.go:60) <Debug> -- Opening SQLite database /var/lib/evebox/events.sqlite
2018-10-29 23:39:00 (migrator.go:66) <Debug> -- Current database schema version: 2
2018-10-29 23:39:00 (resources.go:50) <Warning> -- Failed to find box asset ./resources/sqlite/V3.sql.
2018-10-29 23:39:00 (sqlite.go:94) <Info> -- Retention period: 0 days
2018-10-29 23:39:00 (server.go:446) <Info> -- Configuring internal eve log reader
2018-10-29 23:39:00 (server.go:131) <Info> -- Session reaper started
2018-10-29 23:39:00 (server.go:165) <Info> -- Authentication disabled.
2018-10-29 23:39:00 (bookmarker.go:71) <Info> -- Using bookmark file /var/log/suricata/eve.json.bookmark
2018-10-29 23:39:00 (bookmarker.go:159) <Info> -- Found valid bookmark, jumping to offset 10995
2018-10-29 23:39:00 (server.go:276) <Info> -- Listening on 0.0.0.0:5636
```

**Comment by jasonish** [comment]
Something minor is missing, but probably hard to debug. But I'm curious, so I've spun up an ARM VPS, but it may be a few days until I can tackle this.

The idea is that the web resources are built.. This is a set of static .html and .js files.

These then get archived into the resulting binary for a single binary deployment. The idea is simple, but the execution can be fragile, but once it works it usually keeps working. There must be a minor issue on ARM that I'll try to debug.

**Comment by sgabe** [comment]
Sounds promising, thanks for your efforts. Let me know if I can help with testing.

**Comment by jasonish** [comment]
I went through the process on an arm64 linux box and it more or less worked as expected. It looks like it should for you, given the progress you have made.  Can you try the following:
```
make clean
make
```
given all the deps are installed, this should get a clean build again, with embedded assets.

If that fails I'd like to see:
```
ls -l resources
```
and
```
ls -l resources/public
```
Thanks.

**Comment by sgabe** [comment]
Still no luck.
```
root@pi:~/go/src/evebox # make clean
rm -rf dist
rm -f evebox
rm -rf resources/public
/root/go/bin/packr clean
find . -name \*~ -exec rm -f {} \;
root@pi:~/go/src/evebox # make
cd webapp && make
make[1]: Entering directory '/root/go/src/evebox/webapp'
Exporting GITREV = 3cfd74e.
Building EveBox webapp rev 3cfd74e.
./node_modules/.bin/ng build --aot --prod --output-path ../resources/public --deploy-url "public/"

Date: 2018-10-30T09:28:20.496Z
Hash: 6288f05125412c884814
Time: 212335ms
chunk {0} runtime.cd1930dfc8cce42a4850.js (runtime) 1.45 kB [entry] [rendered]
chunk {1} main.078852891ad1825e3649.js (main) 2.65 MB [initial] [rendered]
chunk {2} polyfills.db84b0d82268f31e7a80.js (polyfills) 59.4 kB [initial] [rendered]
chunk {3} styles.7457cf6e6bb6e4373c6c.css (styles) 0 bytes [initial] [rendered]
make[1]: Leaving directory '/root/go/src/evebox/webapp'
touch resources/public/_done
/root/go/bin/packr -z
CGO_ENABLED=1 go build --tags "fts5 json1" \
        -ldflags "-X \"github.com/jasonish/evebox/core.BuildRev=3cfd74e\" -X \"github.com/jasonish/evebox/core.BuildVersion=0.9.1\" " \
        cmd/evebox.go
root@pi:~/go/src/evebox # ls -l resources
total 1616
-rw-r--r-- 1 root root 1623232 Oct 30 10:28 a_resources-packr.go
drwxr-xr-x 2 root root    4096 Oct 29 18:57 configdb
drwxr-xr-x 2 root root    4096 Oct 28 14:21 elasticsearch
-rw-r--r-- 1 root root    1150 Oct 28 14:21 favicon.ico
drwxr-xr-x 2 root root    4096 Oct 28 14:21 postgres
drwxr-xr-x 2 root root    4096 Oct 30 10:28 public
-rw-r--r-- 1 root root    2252 Oct 28 14:21 resources.go
drwxr-xr-x 2 root root    4096 Oct 28 14:21 sqlite
root@pi:~/go/src/evebox # ls -l resources/public/
total 3720
-rw-r--r-- 1 root root  119616 Oct 30 10:28 3rdpartylicenses.txt
-rw-r--r-- 1 root root       0 Oct 30 10:28 _done
-rw-r--r-- 1 root root    1150 Oct 30 10:28 favicon.ico
-rw-r--r-- 1 root root  165742 Oct 30 10:28 fontawesome-webfont.674f50d287a8c48dc19b.eot
-rw-r--r-- 1 root root  444379 Oct 30 10:28 fontawesome-webfont.912ec66d7572ff821749.svg
-rw-r--r-- 1 root root   77160 Oct 30 10:28 fontawesome-webfont.af7ae505a9eed503f8b8.woff2
-rw-r--r-- 1 root root  165548 Oct 30 10:28 fontawesome-webfont.b06871f281fee6b241d6.ttf
-rw-r--r-- 1 root root   98024 Oct 30 10:28 fontawesome-webfont.fee66e712a8a08eef580.woff
-rw-r--r-- 1 root root     811 Oct 30 10:28 index.html
-rw-r--r-- 1 root root 2653691 Oct 30 10:28 main.078852891ad1825e3649.js
-rw-r--r-- 1 root root   59395 Oct 30 10:28 polyfills.db84b0d82268f31e7a80.js
-rw-r--r-- 1 root root    1447 Oct 30 10:28 runtime.cd1930dfc8cce42a4850.js
-rw-r--r-- 1 root root       0 Oct 30 10:28 styles.7457cf6e6bb6e4373c6c.css
```

**Comment by sgabe** [comment]
I started from scratch and got a `Self test: no embedded index.html found.` message.
```
root@pi:~/go/src/evebox # make
cd webapp && make
make[1]: Entering directory '/root/go/src/evebox/webapp'
Exporting GITREV = 5eb48b1.
Building EveBox webapp rev 5eb48b1.
./node_modules/.bin/ng build --aot --prod --output-path ../resources/public --deploy-url "public/"

Date: 2018-10-30T11:17:11.049Z
Hash: 87641ede10579b3e0b21
Time: 762130ms
chunk {0} runtime.dc451b8418f10e7df718.js (runtime) 1.06 kB [entry] [rendered]
chunk {1} styles.a9a1c8d9a6a1db747c84.css (styles) 0 bytes [initial] [rendered]
chunk {2} polyfills.b8d510370d6f900374c6.js (polyfills) 59.4 kB [initial] [rendered]
chunk {3} main.3ce2c0b84785f72d494d.js (main) 2.99 MB [initial] [rendered]
make[1]: Leaving directory '/root/go/src/evebox/webapp'
touch resources/public/_done
/root/go/bin/packr -z
CGO_ENABLED=1 go build --tags "fts5 json1" \
        -ldflags "-X \"github.com/jasonish/evebox/core.BuildRev=5eb48b1\" -X \"github.com/jasonish/evebox/core.BuildVersion=0.10.0dev\" " \
        cmd/evebox.go
root@pi:~/go/src/evebox # ./evebox server -v -D /var/lib/evebox --datastore sqlite --input /var/log/suricata/eve.json
2018-10-30 12:28:50 (server.go:177) <Info> -- This is EveBox Server version  (rev: ); os=linux, arch=arm
2018-10-30 12:28:50 (server.go:257) <Error> -- Self test: no embedded index.html found.
2018-10-30 12:28:50 (geoip-service.go:44) <Warning> -- Failed to initialize geoip database: no database files found
2018-10-30 12:28:50 (configdb.go:59) <Info> -- Using configuration database file /var/lib/evebox/config.sqlite
2018-10-30 12:28:50 (migrator.go:66) <Debug> -- Current database schema version: 1
2018-10-30 12:28:50 (sqlite.go:140) <Info> -- Configuring SQLite datastore
2018-10-30 12:28:50 (sqlite.go:146) <Info> -- SQLite event store using file /var/lib/evebox/events.sqlite
2018-10-30 12:28:50 (sqlite.go:60) <Debug> -- Opening SQLite database /var/lib/evebox/events.sqlite
2018-10-30 12:28:50 (migrator.go:66) <Debug> -- Current database schema version: 2
2018-10-30 12:28:50 (sqlite.go:94) <Info> -- Retention period: 0 days
2018-10-30 12:28:50 (server.go:455) <Info> -- Configuring internal eve log reader
2018-10-30 12:28:50 (server.go:131) <Info> -- Session reaper started
2018-10-30 12:28:50 (server.go:165) <Info> -- Authentication disabled.
2018-10-30 12:28:50 (bookmarker.go:71) <Info> -- Using bookmark file /var/log/suricata/eve.json.bookmark
2018-10-30 12:28:50 (server.go:276) <Info> -- Listening on 0.0.0.0:5636
2018-10-30 12:28:50 (bookmarker.go:159) <Info> -- Found valid bookmark, jumping to offset 2012
```

**Comment by sgabe** [comment]
It turns out that I did not clone the repository into `$GOPATH/src/github.com/jasonish/evebox` but `$GOPATH/src/evebox`. One most exactly follow the instructions:

>First checkout Evebox into your GOPATH, ~~for example~~:
>```
>git clone https://github.com/jasonish/evebox.git \
>    $GOPATH/src/github.com/jasonish/evebox
>```

I can confirm that building on Raspberry Pi 3 Model B+ was successful. However, I got a SIGSEGV after a few events came in.
```
root@pi:~/go/src/github.com/jasonish/evebox # ./evebox server -v -D /var/lib/evebox --datastore sqlite --input /var/log/suricata/eve.json
2018-10-30 14:21:20 (server.go:177) <Info> -- This is EveBox Server version 0.10.0dev (rev: 5eb48b1); os=linux, arch=arm
2018-10-30 14:21:20 (server.go:259) <Info> -- Self test: found embedded index.html.
2018-10-30 14:21:20 (geoip-service.go:44) <Warning> -- Failed to initialize geoip database: no database files found
2018-10-30 14:21:20 (configdb.go:59) <Info> -- Using configuration database file /var/lib/evebox/config.sqlite
2018-10-30 14:21:20 (migrator.go:66) <Debug> -- Current database schema version: 1
2018-10-30 14:21:20 (sqlite.go:140) <Info> -- Configuring SQLite datastore
2018-10-30 14:21:20 (sqlite.go:146) <Info> -- SQLite event store using file /var/lib/evebox/events.sqlite
2018-10-30 14:21:20 (sqlite.go:60) <Debug> -- Opening SQLite database /var/lib/evebox/events.sqlite
2018-10-30 14:21:20 (migrator.go:66) <Debug> -- Current database schema version: 2
2018-10-30 14:21:20 (sqlite.go:94) <Info> -- Retention period: 0 days
2018-10-30 14:21:20 (server.go:455) <Info> -- Configuring internal eve log reader
2018-10-30 14:21:20 (server.go:131) <Info> -- Session reaper started
2018-10-30 14:21:20 (server.go:165) <Info> -- Authentication disabled.
2018-10-30 14:21:20 (bookmarker.go:71) <Info> -- Using bookmark file /var/log/suricata/eve.json.bookmark
2018-10-30 14:21:20 (bookmarker.go:159) <Info> -- Found valid bookmark, jumping to offset 2425
2018-10-30 14:21:20 (server.go:276) <Info> -- Listening on 0.0.0.0:5636
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1d5e4]

goroutine 19 [running]:
runtime/internal/atomic.goXadd64(0x24b4774, 0x1, 0x0, 0x23a2000, 0x1)
        /usr/local/go/src/runtime/internal/atomic/atomic_arm.go:96 +0x1c
github.com/jasonish/evebox/vendor/github.com/ua-parser/uap-go/uaparser.(*Parser).ParseUserAgent(0x21542a0, 0x2146ca0, 0x18, 0x0)
        /root/go/src/github.com/jasonish/evebox/vendor/github.com/ua-parser/uap-go/uaparser/parser.go:262 +0xb8
github.com/jasonish/evebox/vendor/github.com/ua-parser/uap-go/uaparser.(*Parser).Parse.func1(0x23b0664, 0x21542a0, 0x2146ca0, 0x18, 0x23ac330)
        /root/go/src/github.com/jasonish/evebox/vendor/github.com/ua-parser/uap-go/uaparser/parser.go:224 +0x68
created by github.com/jasonish/evebox/vendor/github.com/ua-parser/uap-go/uaparser.(*Parser).Parse
        /root/go/src/github.com/jasonish/evebox/vendor/github.com/ua-parser/uap-go/uaparser/parser.go:221 +0x194
```

**Comment by jasonish** [comment]
> It turns out that I did not clone the repository into `$GOPATH/src/github.com/jasonish/evebox` but `$GOPATH/src/evebox`. One most exactly follow the instructions:
> 
> > First checkout Evebox into your GOPATH, for example:
> > ```
> > git clone https://github.com/jasonish/evebox.git \
> >    $GOPATH/src/github.com/jasonish/evebox
> > ```

Yeah, this is just part of developing with Go. New features in the language are making it less sensitive to this, but I haven't adapted those yet.

Re. the SIGSEGV...

I build on a Scaleway system, its appears to be an arm64, with an armv8. It looks like the Raspberry Pi 3 Model B+.  Anyways, this crash appears to be in the user agent parser which is a 3rd party library. Can you try a:
```
dep ensure -update -v
```
then a ```make``` and try again?

Failing that we could try commenting out the call to the user agent parser and see if that gets you up and running...  Then I'd consider disabling that an ARM if its not reliable.

**Comment by sgabe** [comment]
I rebuilt it but the issue still persists. It works for a while and then crashes.

**Comment by jasonish** [comment]
In file `cmd/server/server.go`, remove line 473:
```
        eveFileProcessor.AddFilter(&useragent.EveUserAgentFilter{})
```
rebuild and try again.

**Comment by sgabe** [comment]
Note that I also had to comment out line 46 in `cmd/server/server.go` and I am still testing, however, it seems to be working now.
```
        "github.com/jasonish/evebox/useragent"
```

**Comment by jasonish** [comment]
Keep me posted. I think making this user-agent parsing an option might be a solution. As far as I can tell, I don't think I'm doing anything wrong, but maybe the library is. I'll let my arm instance run for a while longer and see if it happens..

**Comment by markVnl** [comment]
Building go in arm, 32 and 64 bit, is not the problem, even cross complying is not that hard.

However node-sass is not available of arm and it does not build in the tree out of the box.
With a minor patch it builds happily on arm, see this rejected PR:
https://github.com/sass/node-sass/pull/2253/commits/a6fd82438611377331b042eac6958c534649859a 
  

With smal adjustment to the Makefile I was able to build it on Fedora F27 armv7hl and aarch64 (ie arm and arm64, in the rpm world they messed up the names a bit) 

```
@@ -90,6 +93,14 @@
 ifeq ($(GOARCH),386)
 dist: DISTARCH := x32
 endif
+ifeq ($(GOARCH),arm)
+dist: DISTARCH := armv7hl
+endif
+endif
+ifeq ($(GOARCH),arm64)
+dist: DISTARCH := aarch64
+endif
+export $(DISTARCH)
 ifneq ($(VERSION_SUFFIX),)
 dist: VERSION := latest
 endif
```
This of cause after repacking node-sass in the build tree with the arm compiled one.

You may need to do some work at the packing section to if packaging is your goal..

Grtz Mark

**Comment by jasonish** [comment]
I've recently started saving the generate webapp artifacts in the gitlab-ci to potentially make it easier to build where node, and the angular stack may be a pain. Not sure if it would be of use yet: 

https://gitlab.com/jasonish/evebox/-/jobs/115548951/artifacts/browse

**Comment by sgabe** [comment]
I read that node-sass is not available for ARM. However, building on ARMv7l seemed to be successful, or at least I did not see any errors.

**Comment by sgabe** [comment]
@markVnl please correct me if I am wrong, but based on https://github.com/sass/node-sass/issues/1609#issuecomment-228739111 my understanding is that if node-sass is not available it may still be able to compile locally during the build process. I am not sure whether node-sass is a requirement or just optional. However, in the past few days, I have successfully rebuilt EveBox numerous times on Raspberry Pi 3 Model B+ (which is actually ARMv8 reported as armv7l) without any node-sass related issues.

**Comment by markVnl** [comment]
@sgabe IIRC the evebox build did deliver a (go-bind) binary without a arm complied node-sass; 
but the the webapp obviously does not work.

**Comment by markVnl** [comment]
Well is a long time ago, and much has changed for the good. 

Node-sass builds automatically in the source-tree if the architecture is not supported; 
hence evebox builds fine on arm 32 and 64 bit. 

Moreover I saw the public-recoures precomplied in the repository so you do not need to worry about the node stack at all if you wish.

**Comment by mfyuce** [comment]
Thanks for the good works,

As I gather from this thread and later developments, there is no problem (?) [now] including arm[Raspberry PI][64] binaries into the releases (https://evebox.org/files/release/latest/). 

I am now able to generate the binaries for Raspberry PI through;

> env GOARCH=arm64 GOARM=6 CC=aarch64-linux-gnu-gcc make dist
> 
> env GOARCH=arm GOARM=6 CC=arm-linux-gnueabi-gcc make dist

Will try the resulting binaries on Raspberry PI soon.

**Comment by mfyuce** [comment]
It seems Raspberry PI is 32 and it is working nicely (after following proposed changes here).

Also on Docker Centos:7, couldn't make it build on gitlab, so made it with Ubuntu:16 without macos, for now.

Also, any idea how to see DHCP logs in evebox? So far no luck on that...

All the best...

**Comment by jasonish** [comment]
> Also, any idea how to see DHCP logs in evebox? So far no luck on that...

I've created a new issue for DHCP:
https://github.com/jasonish/evebox/issues/124

**Comment by jasonish** [comment]
Closing as ARM support is more about the build tooling than EveBox itself.

**Comment by mfyuce** [comment]
Thank you, I think, it would be nice officially supporting it. As there are some stability issues on raspberry. I.e. cannot stay alive on the long run etc.

**Comment by jasonish** [comment]
> Thank you, I think, it would be nice officially supporting it. As there are some stability issues on raspberry. I.e. cannot stay alive on the long run etc.

I think someone would have to step up and take on that role of supporting it. I'm happy to do my best to take fixes to keep it working on ARM, the Pi, etc. But do not use those architectures myself.

They are also of limited use.  The typically use case needs Elastic Search, which is probably a bit much for a Raspberry Pi anyways, so you could move the EveBox server to wherever you host Elastic Search.  And SQLite isn't very useful other than some quick demonstrations.

The more intersting bit would be stability issues of the agent side an ARM.

**Comment by thiscantbeserious** [comment]
> They are also of limited use

Well, ARM64 has arrived in Datacenters, Workstations and for High Performance Server solutions that are far away from what you're likely used in the RaspberryPi - the advantage to that is that they use the same architecture as those low cost SBC-Boards - and these newer SBCs powered like by the RK3399 SoC also bring native PCIe, so they aren't crippled like the RaspberryPi 4 - one example would be the [NanopiM4V2](https://www.friendlyarm.com/index.php?route=product/product&product_id=268), or the [RockPi 4](https://wiki.radxa.com/Rockpi4) which have an 6-Core CPU and 4GB DDR4-Ram - and ARMv8 also has better Cryptographic Acceleration than many Atom-CPUs with AES-Ni ([source](https://github.com/ThomasKaiser/sbc-bench/blob/master/Results.md)).

ARM support in Mainline is also increasing: https://www.linux-arm.info/index.php/kernel as are many bigger Vendors moving from MIPS to ARM like Ubiquiti with the [Dream Machine](https://store.ui.com/products/unifi-dream-machine)

Some seriously powerfull hardware:

https://www.solid-run.com/nxp-lx2160a-family/honeycomb-workstation/
https://www.nxp.com/products/processors-and-microcontrollers/arm-processors/layerscape-communication-process/layerscape-lx2160a-multicore-communications-processor:LX2160A

If even FreeBSD is [close to moving ARM to a Tier 1 architecture](https://lists.freebsd.org/pipermail/freebsd-arm/2019-December/020867.html
) I believe things are shifting a bit and should warrant a more serious look at ARM then just thinking about it being a toy-platform for everything and nothing (usually the RaspberryPi).

One of the first boards to support it officially with PFSense is the [Netgate SG-1100](https://store.netgate.com/pfSense/SG-1100.aspx) based on the [EspressoBin v7](http://espressobin.net/announcing-espressobin-v7-revision/)

**Comment by jasonish** [comment]
Travis now has an ARM builder, so at the very least I can start doign CI on ARM, but I probably won't offer builds (well, maybe, but I think they only offer one arm type).

But, a bigger picture question... How are people using EveBox on ARM? Just as a log sender to a bigger system? Using ElasticSearch on the ARM device? Using the SQLite datastore? I'd like some feedback on this please.

**Comment by mfyuce** [comment]
Hi,

First thank you on the decision.

Anything is appreciated.

My use case is; 

- Collecting the logs on the device Evebox is running  with sqlite (storage size on the device is enough for the requirements at hand, but if need arise, collection interval may be decreased to accommodate the storage size on the device etc.)

- and periodically zipping/signing and sending it to a storage location on some backup location (for now.... Later, elastic search, syslog etc. support will be added) to be stored for a period of time.

- then, ..., other things will be done on the storage location without the need of the device. 

All the best,
Mehmet.

PS: I can also offer my programmatic help, if you can guide me on how to help.

**Comment by sgabe** [comment]
I have used EveBox and the built-in SQLite datastore on a Raspberry Pi 3 Model B+ with a 1 day retention policy as when the database reached 1GB in size the Pi got unstable. I have checked the events every day anyway so it wasn't an issue. However, later I have implemented SELKSE on another small server with more resources.

**Comment by jasonish** [comment]
Playing with a Rust rewrite, it becomes trival to cross build to arm... If anyone wants to try it out, there is an armv7-linux build in the CI output here: https://github.com/jasonish/evebox/actions/runs/117147411

**Comment by jasonish** [comment]
Closing. Added Arm builds to CI, as well as my own build processs. Tested in Raspberry Pi 4.

**Comment by markVnl** [comment]
Will test if time found;

Thank You

**Comment by mfyuce** [comment]
Hi,

Thank you very much for the good work. Really appreciated.

Tried on armv6 on Raspberry PI and it is very stable.

For this, created a branch `https://github.com/mfyuce/evebox/tree/new_arm_build` and tried generating armv6 binaries using github CI. The only thing problematic is the `docker` stage (https://github.com/mfyuce/evebox/runs/895612161?check_suite_focus=true). Could not make it work but could get armv6 binaries and was OK for me. Kindly could you check What I was doing wrong? I could send a PR if you say it is OK generating armv6 binaries..

All the best,

**Comment by jasonish** [comment]
@mfyuce Can you try this ARM build and see if it runs on your RPi?

https://evebox.org/files/development/evebox-latest-linux-arm.zip

**Comment by mfyuce** [comment]
Hi @jasonish ,

It runs without a problem.

**Comment by jasonish** [comment]
> Hi @jasonish ,
> 
> It runs without a problem.

Cool. I've added these to my regular builds. Thanks for testing.
