### ISSUE TITLE
Execute custom actions on alerts

### ISSUE THREAD

**Issue by sgabe** [jasonish/evebox#82]
I wanted an easy way to add the source IP address of an alert to an address list on a MikroTik router, hence I decided to [fork](https://github.com/sgabe/evebox) your repository and add the missing pieces.

I ended up with the [routeros](https://gopkg.in/routeros.v2 ) Go client library for accessing MikroTik devices using the RouterOS API. The idea is to add or remove the source IP address of an alert to or from an address list on a MikroTik device by invoking the RouterOS API when an alert is escalated or de-escalated.

The above serves me well, however, it would be nice to have a general approach (e.g. some kind of plugin system or just a Go interface for a start) to implement custom actions for alerts that could be triggered from the web interface or via an API call.

**Comment by jasonish** [comment]
Closing as right now I feel this is out of scope.
