### ISSUE TITLE
Wrong query path /api/1/config when using an nginx reverse proxy and sub directory

### ISSUE THREAD

**Issue by haam3r** [jasonish/evebox#84]
# Description

With the latest stable release, when Evebox is behind a Nginx reverse proxy and additionally located in a subdirectory, loading the webinterface fails.

## Error log

The browser console logs the following error:
```
polyfills.86a71be0f0e82f9b8a11.js:1 GET https://[IP.ADDRESS.HERE]/api/1/config 404
```

## Additional info
Relevant Nginx config section (https://github.com/cert-ee/s4a/blob/master/saltstack/salt/detector/files/nginx/sites-available/default.jinja#L80-L83):
```
location /evebox {
                rewrite /[^\/]+(.*) $1  break;
                proxy_pass http://127.0.0.1:5636;
        }
```

**Comment by jasonish** [comment]
Fixed. Releasing as 0.10.1 to also address https://github.com/StamusNetworks/SELKS/issues/152.
