### ISSUE TITLE
Timezone Awareness + " ago" template

### ISSUE THREAD

**Issue by demospace** [jasonish/evebox#86]
It doesn't seem like Evebox is time zone aware?

When log data makes its way into ES with timestamps in UTC, but is displayed on a machine with a timezone set as America/Chicago, the human-readable time differences are both incorrect, and in this case in the wrong direction (I'm UTC -6, but it says the events were "6 hours ago").

I believe the relevant code is here: https://github.com/jasonish/evebox/blob/3cfd74e2f450e099303996317b957d801ca5c753/webapp/src/app/duration.component.ts#L31-L51

Would it be possible to add a timezone or tz offset to the settings.yaml and account for it here?

**Comment by jasonish** [comment]
I'd rather look at why this is happening and doesn't just work.  So do your eve records log with UTC?  Mine look like:
```
{"timestamp":"2018-12-20T15:32:10.000435-0600","flow_id":700451335607952
```
do you get UTC there instead of -0600? Just so I can replicate.

**Comment by jasonish** [comment]
And do you see the same thing in the "Events" view?

**Comment by jasonish** [comment]
I've switched my Suricata box to log in UTC...  Here is an example of event that's been parsed/indexed into Elastic Search:
```
{
  "_id": "01CZ6RYPEBY4S5ZQNFPNAZF1R3",
  "_index": "logstash-2018.12.20",
  "_score": null,
  "_source": {
    "@timestamp": "2018-12-20T21:39:43.179Z",
    "alert": {
      "action": "allowed",
      "category": "Potentially Bad Traffic",
      "gid": 1,
      "metadata": {
        "created_at": [
          "2010_09_23"
        ],
        "updated_at": [
          "2010_09_23"
        ]
      },
      "rev": 7,
      "severity": 2,
      "signature": "GPL ATTACK_RESPONSE id check returned root",
      "signature_id": 2100498
    },
    "app_proto": "http",
    "dest_ip": "10.16.1.11",
    "dest_port": 46732,
    "event_type": "alert",
    "flow": {
      "bytes_toclient": 570,
      "bytes_toserver": 419,
      "pkts_toclient": 4,
      "pkts_toserver": 5,
      "start": "2018-12-20T21:39:42.755810+0000"
    },
    "flow_id": 1113386722953314,
    "http": {
      "hostname": "www.testmyids.com",
      "http_content_type": "text/html",
      "http_method": "GET",
      "http_user_agent": "curl/7.61.1",
      "length": 39,
      "protocol": "HTTP/1.1",
      "status": 200,
      "url": "/",
      "user_agent": {
        "major": "7",
        "minor": "61",
        "name": "curl",
        "patch": "1"
      }
    },
    "in_iface": "enp4s0f0",
    "proto": "TCP",
    "src_ip": "217.160.0.187",
    "src_port": 80,
    "tags": [],
    "timestamp": "2018-12-20T21:39:43.179731+0000"
  },
  "_type": "doc",
  "sort": [
    1545341983179
  ]
}
```

Yet it still shows up a minutes ago, not 6 hours ago. I'll have to understand more about your time setup and why this is happening to even test such as adjustment.

**Comment by demospace** [comment]
Ah, yes, I see the issue. First let me give you this context: I'm trying to use EveBox with an existing Graylog installation. Graylog is receiving JSON logs from Suricata, but then normalizing them before entry into ES.

So the EVE JSON comes across as: {"timestamp":"2018-12-20T15:37:56.000805-0600"}, but goes into ES as 

{"timestamp": "2018-12-20 21:28:55.226"}
and also
{"@timestamp": "2018-12-20T21:28:55.226Z"} (to account for logstash)

The former isn't parsed via eg the PCAP API, and the latter isn't in terms of the time offsets.

This isn't any fault of EveBox obviously. I'll have to look at trying to store the raw JSON in ES to work with EveBox. Apologies for the confusion.

**Comment by demospace** [comment]
I am fixing this so the timestamps conform to what logstash would deliver, but FWIW the "Z" UTC format is valid according to [ISO_8601](https://en.wikipedia.org/wiki/ISO_8601)

**Comment by demospace** [comment]
For anyone that stumbles on this in the future: Graylog is using a Java library that doesn't have microsecond precision. No matter the parse_date options you use, the timestamp from the EVE JSON will always be truncated if the datatype is a date. Sadly Graylog uses the "timestamp" ES field internally and will force whatever date you give it into a date datatype and will truncate it. This means that it's incompatible with EveBox without a mapping or manual recode. :(

Don't waste an evening like I did!

**Comment by jasonish** [comment]
Yeah, Graylog must be doing something. It might be worth noting that Elastic Search only has millisecond precision.  For example, Suricata logs:
```
"timestamp": "2018-12-21T03:57:35.624143+0000",
```
indexing into Elastic Search creates the `@timestamp` field like:
```
"@timestamp": "2018-12-21T03:57:35.624Z"
```

Which is fine. The example you show me above loses the time zone information though.
