### ISSUE TITLE
Docs: Adding a User (minor)

### ISSUE THREAD

**Issue by demospace** [jasonish/evebox#89]
The documentation [here](https://evebox.readthedocs.io/en/latest/authentication.html#adding-a-user) gives the following command to add a user:

> evebox config users -D /var/lib/evebox add --username joe

On my installation the -D or --data-directory switch need to appear before "users" to be effective eg

> evebox config -D /var/lib/evebox users add --username joe

**Comment by demospace** [comment]
This is so minor I don't think it deserves an open issue, and I'm not sure where else to put it:

In the default .yaml under event services below should read "event-type" (event-types isn't a valid field and throws errors).
```
    # Only make available for alert types.
    event-types:
      - alert
```

**Comment by jasonish** [comment]
> In the default .yaml under event services below should read "event-type" (event-types isn't a valid field and throws errors).

I'm not sure about this.  The only usage I see for "event-type" or "event-types" is "event-types" in webapp/src/app/eventservices.service.ts.

**Comment by jasonish** [comment]
Thanks. Closing. Documentation has been fixed. And I can't find an issue with the event-types field.
