### ISSUE TITLE
size parameter from config file ist not applied correct.

### ISSUE THREAD

**Issue by dfirbuddy** [jasonish/evebox#9]
If you change the number of elements to see on a page, the calculation of the start address of the next junk is calculated wrong. 
With size= 200 I would expect start addresses 1, 201, 401. But I get 1, 101,201,301 ...
The number of columns is always correct.

**Comment by jasonish** [comment]
Should be fixed in master now.  

1) The page size configured at the server was being ignored by the pager.

2) You may have had a page size cached in localStorage if you used an older version that allowed the page size to be set at the client.

**Comment by dfirbuddy** [comment]
Are you sure that the patch is working? After upgrade to the latest version I see only the menu, no date at all.
Did I miss something?

**Comment by jasonish** [comment]
Date?  Do you mean you are only seeing the menu, and no events?  If so, try
to clear your browser cache or do a force refresh.  I have no implemented
caching breaking filenames yet.

**Comment by dfirbuddy** [comment]
Its strange, my friend (dfirdude)  has had the same problem ...
Same Problem with IE and Firefox
cache cleaned


Am 10.03.2015 um 20:06 schrieb Jason Ish:

**Comment by dfirdude** [comment]
Took a closer look: I got the error message "Error: localConfig.elasticSearch is undefined" in the Firefox Web Console.
After commenting line 60 in scripts/service.config.js, things worked fine in Firefox (not in IE).

**Comment by jasonish** [comment]
Lets try that fix again.  Was trying to cleanup a local storage value that may not exist.  Should be fixed in master.

**Comment by dfirdude** [comment]
Yep, seems o.k. now! Thanks!
