### ISSUE TITLE
Authenticated Users - PCAP Link Fails

### ISSUE THREAD

**Issue by demospace** [jasonish/evebox#90]
Downloading the PCAP for a packet works with
`authentication:
  required: false
`
It looks like x-evebox-session-id is sent in the request headers in this scenario.

Once authentication is enabled and a user logs in, the link to download the PCAPs fails in Chrome with "ERR_INVALID_RESPONSE." Console shows no errors. Request Headers are listed as "Provisional" and contain:

```
Content-Type: application/x-www-form-urlencoded
DNT: 1
Origin: http://IP:5636
Referer: http://IP:5636/
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
```

Is it possible the session header isn't being sent? Or is there some kind of CORS issue with the POST? I don't see much else on the client side.

**Comment by demospace** [comment]
I'm not exactly sure how this is handled:

https://github.com/jasonish/evebox/blob/30c1aca7a5286540057431a65b0d53b56fdfbd4c/webapp/src/app/api.service.ts#L219-L239

Does the form submission there include the session headers? Similar functions seem to do things like this.client.get(foo) or this.post(foo) which I think would keep the headers?

**Comment by jasonish** [comment]
As this is not a REST/XHR request, I can't set the header.  I've fixed this by setting a short lived cookie with the session ID that will be tested in addition to the session header.
