### ISSUE TITLE
Could not load worker ReferenceError: global is not defined

### ISSUE THREAD

**Issue by biolds** [jasonish/evebox#91]
Using Evebox 0.10.1 (Rev: c17f18b), I'm having an issue, in the Inbox, when clicking on an alert, this error is logged (though Evebox continues to work, and does not show an error message):

![screenshot_20181226_152141](https://user-images.githubusercontent.com/4569027/50448802-7e5c6300-0923-11e9-907d-bdb399868f42.jpg)

After that, clicking on the alert id, leads to the Event page, from there clicking on an event shows a blank page, and a popup flashes with "Unhandled error" message (i was not fast enough to keep the popup in the screenshot below):

![screenshot_20181226_152247](https://user-images.githubusercontent.com/4569027/50448806-84524400-0923-11e9-90ea-dfa8fa54cabc.jpg)

**Comment by jasonish** [comment]
I see the first issue, however, I don't understand this:
```
After that, clicking on the alert id, leads to the Event page
```
From where are you clicking on the alert ID?
Thanks.

**Comment by biolds** [comment]
Sorry, after clicking on the alert in the inbox, I click on the "Signature ID" field from alert currently opened

**Comment by jasonish** [comment]
Can you try the latest development build. I think I may have fixed this. Thanks.

**Comment by biolds** [comment]
Yes, it fixed it, thanks!
