### ISSUE TITLE
windows released doesn't have pager on report

### ISSUE THREAD

**Issue by Kamalifar** [jasonish/evebox#92]
Hi Jason,

I appreciated for this great project.
I'd like use the evebox on windows so I downloaded the windows version (0.1.0.1) from your evebox.org. On the report I select `Event Type: All` to see all events when I click on oldest button I go to latest records and when I click on newest button I go to first records, however, I couldn't use newer and older button to go to middle records. Is there any configuration to access to middle records. assume that the all records are one hundred thousand.

Regards.

**Comment by jasonish** [comment]
I think this is a generic issue not specific to Windows.  I'm aware of it and hope to have it fixed soon.

**Comment by Kamalifar** [comment]
The windows released doesn't have graph report, does have?

**Comment by jasonish** [comment]
> The windows released doesn't have graph report, does it have?

If using Elastic Search yes. If not, then no. Work in progress.

**Comment by jasonish** [comment]
The pager should now be fixed in git master.
