### ISSUE TITLE
Comprehensive report for multi json files on Embedded SQLite Database mode

### ISSUE THREAD

**Issue by Kamalifar** [jasonish/evebox#93]
I use the evebox in `Embedded SQLite Database` mode in windows release version with the below command:

`evebox -v -D . --datastore sqlite --input /var/log/suricata/eve.json`

 I have some files that I've already backed up from suricata (json file). I'd like to create a comprehensive report from all my files.

How can I do it?

**Comment by jasonish** [comment]
At this time reporting is only available with an Elastic Search backend. Its on the some day/maybe list.  Probably when I work further on the PostgreSQL support, SQLite will also benefit from that.

**Comment by Kamalifar** [comment]
I added the json files one by one manually. the evebox command line display that committed the events when I replace the eve.json with another one.

In your opinion, did this gather all log and integrate them?

**Comment by jasonish** [comment]
What was your command line for adding them one by one?

**Comment by Kamalifar** [comment]
I copied a `eve.json` file and ran this command first:

`evebox -v -D . --datastore sqlite --input /var/log/suricata/eve.json`

then I wait for committing all records then replace another `eve.json` and so on.

**Comment by jasonish** [comment]
That should keep them all available then.

**Comment by Kamalifar** [comment]
That's great. Thanks a lot.

**Comment by jasonish** [comment]
Closing as a support request.  Issue #95 opened for reporting with SQLite.
