### ISSUE TITLE
Multiple inputs to esimport

### ISSUE THREAD

**Issue by envyes** [jasonish/evebox#98]
Hello
We are planning to run multiple eve instances in our setup. In addition we would like to send some evefiles to elasticsearch using esimport. Currently, the code supports only single input file. Are there plans to add multiple inputs to esimport? Or any suggestions how we can achieve this with the current version?
Thanks in advance
Nidhi.

**Comment by envyes** [comment]
Hello Jason

We have not investigated evebox agent since we wanted to send our data to
elasticsearch and esimport handled it perfectly. I'll try with multiple
esimport processes though and see if we can achieve this.

Many thanks
Nidhi.

**Comment by jasonish** [comment]
Makes sense since esimport goes directly to Elastic Search and the agent doesn't.  I may took at look at adding this soon.

**Comment by envyes** [comment]
Thanks, that would be helpful.

-Nidhi

**Comment by jasonish** [comment]
I took a look at this, and I think it makes sense to add this functionality.  There would be a breaking change though.

Right now I have --bookmark and --bookmark-filename, where --bookmark-filename is required if --bookmark is in use.  That doesn't apply to well if multiple inputs are using.  So I'd probably remove those options and simply have --bookmark-directory. This directory would contain the bookmarks, where each bookmark file is a hash of the path being used.

**Comment by jasonish** [comment]
I've added support for multiple files to `esimport`.

You can either specify multiple eve files on the command line or convert the `input` parameter in the config file to a list. 

See: https://github.com/jasonish/evebox/blob/esimport/multiple-files/doc/esimport.yaml#L1

This branch also changes the default index from `evebox` to `logstash`. So if you aren't explicitly setting it, you might want to.

Builds from this branch can be downloaded here:
https://gitlab.com/jasonish/evebox/-/jobs/160376788/artifacts/browse

I'll be testing this myself over the next few days before merging back to `master`.

**Comment by envyes** [comment]
Hello Jason

Thank you so much for implementing this.

Regards
Nidhi.

**Comment by jasonish** [comment]
Featured merged into master.
