### ISSUE TITLE
Reports - aggregate numbers/graph incorrect

### ISSUE THREAD

**Issue by blachine** [jasonish/evebox#99]
Looking for assistance to help solve the following two issues:

1.  In the reports section, section/category/source/destination type data is populated but the aggregate numbers for each are all zero.  This is the same issues across the following reports:  Alerts, DNS, SSH and Flow.  All aggregate counts for all reports indicate '0'.

2.  In addition, the graph at the top of the page is not illustrated as expected, total number instances are shown but as a single aggregate value, not over time individually over time.  This applies to Alerts, DNS and SSH.  The flow graph appears to be correct, though aggregate counts are as per 1) above.

The pertinent version details are: 
 
evebox-0.10.1-1.x86_64.rpm
elasticsearch 6.5.1
OpenSuse - LEAP 15.0

![alert_page_image](https://user-images.githubusercontent.com/24867140/51565413-015bd500-1e60-11e9-846d-0c87df4ae21a.PNG)

**Comment by jasonish** [comment]
Can you tell me how you are putting alerts into Elastic Search please?

**Comment by jasonish** [comment]
I've seen this myself now. In some cases a forced page reload fixes it. Can you check if that fixes things on your end?

Have you modified the "logstash" Elastic Search template at all?

**Comment by jasonish** [comment]
Should be fixed in latest development builds.  I'll be doing a new point release soon with this and a few other bug fixes.
